{
  "hash": "5c5e7e5ad3cf8560c4e59066d9647904",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"IA para Científicos Sociales\"\nsubtitle: \"Sesión 1.4: Laboratorio 2 - Validación cruzada y comparación de modelos\"\nauthor:\n  - name: Danilo Freire\n    orcid: 0000-0002-4712-6810\n    email: danilofreire@gmail.com\n    affiliations: \"Department of Data and Decision Sciences <br> Emory University\"\nformat:\n  clean-revealjs:\n    self-contained: true\n    footer: \"[Sesión 1.4](https://danilofreire.github.io/introduccion-ia-ucu/clases/dia-01/04-laboratorio-02.html)\"\n    transition: slide\n    transition-speed: default\n    scrollable: true\nrevealjs-plugins:\n  - multimodal\nengine: knitr\neditor:\n  render-on-save: true\nlang: es\n---\n\n\n\n# Laboratorio 2: Validación cruzada y comparación de modelos {background-color=\"#2d4563\"}\n\n## Objetivos del laboratorio\n\n:::{style=\"margin-top: 30px; font-size: 26px;\"}\n:::{.columns}\n:::{.column width=50%}\n**Lo que vamos a hacer:**\n\n1. Volver al dataset del laboratorio 1\n2. Análisis exploratorio extendido\n3. Feature engineering básico\n4. Validación cruzada en 5 folds\n5. Comparar regresión logística vs. árbol\n6. Evaluar el mejor modelo en test\n:::\n\n:::{.column width=50%}\n**Lo que vamos a practicar:**\n\n- Decisiones de [preprocesamiento]{.alert}\n- [Comparación]{.alert} sistemática de modelos\n- [Visualización]{.alert} de resultados\n- [Interpretación]{.alert} de modelos\n\n:::{style=\"margin-top: 30px; font-size: 28px;\"}\n[Hay menos código predefinido. ¡Ustedes van a escribir más!]{.alert}\n\n[¡No se preocupen! Les damos una estructura para que puedan completar]{.alert} 😉\n:::\n:::\n:::\n:::\n\n## Del lab 1 al lab 2\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n:::{.columns}\n:::{.column width=50%}\n**En el lab 1 hicimos:**\n\n- Cargamos `indicadores_mundiales.csv`\n- [Una sola]{.alert} división train/test\n- Un modelo: regresión logística\n- Métricas en test: precision, recall, ROC-AUC\n- Discutimos el [umbral]{.alert} de decisión\n:::\n\n:::{.column width=50%}\n**Hoy vamos un paso más allá:**\n\n- [El mismo dataset]{.alert}, los mismos predictores\n- [Validación cruzada]{.alert} (5 folds) en lugar de una sola partición\n- [Dos]{.alert} modelos a comparar: logístico vs. árbol\n- Feature engineering: ¿una variable nueva ayuda?\n- Evaluación final en test\n:::\n:::\n\n[El objetivo sustantivo sigue siendo el mismo: predecir `crecimiento_alto` a partir de indicadores macro]{.alert}\n:::\n\n# Parte 1: Carga y exploración {background-color=\"#2d4563\"}\n\n## Cargar los paquetes\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Cargar paquetes\n# install.packages(c(\"tidymodels\", \"tidyverse\", \"rpart\")) # Instalar si es necesario\nlibrary(tidymodels)\nlibrary(tidyverse)\nlibrary(rpart) # Para el motor de árbol de decisión\n\n# Configurar tema de ggplot\ntheme_set(theme_minimal(base_size = 14))\n```\n:::\n\n\nO de una forma más automatizada:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npaquetes <- c(\"tidymodels\", \"tidyverse\", \"rpart\")\n\n# require(): intenta cargar el paquete y devuelve TRUE/FALSE\n# Si no está instalado (FALSE), lo instala y carga\n# character.only = TRUE: pkg es una variable; sin esto, R buscaría un paquete llamado \"pkg\"\nfor (pkg in paquetes) {\n  if (!require(pkg, character.only = TRUE)) {\n    install.packages(pkg, dependencies = TRUE)\n    library(pkg, character.only = TRUE)\n  }\n}\n```\n:::\n\n:::\n\n## El dataset: indicadores mundiales\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\nVolvemos al dataset de [indicadores mundiales]{.alert} que ya usamos en el lab 1:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Cargar datos\ndatos <- read_csv(\"datos/indicadores_mundiales.csv\")\n# Lean el archivo directo desde la web:\n# datos <- read_csv(\"https://raw.githubusercontent.com/danilofreire/introduccion-ia-ucu/main/clases/dia-01/datos/indicadores_mundiales.csv\")\n\n# Ver estructura\nglimpse(datos) # Ver las variables y tipos\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 179\nColumns: 11\n$ pais                    <chr> \"Angola\", \"Argelia\", \"Benín\", \"Botsuana\", \"Bur…\n$ continente              <chr> \"África\", \"África\", \"África\", \"África\", \"Áfric…\n$ gasto_educacion         <dbl> 5.7, 4.0, 3.2, 5.0, 4.6, 4.8, 4.6, 4.3, 5.9, 5…\n$ acceso_internet         <dbl> 50.2, 48.0, 34.3, 46.2, 62.5, 66.0, 55.5, 39.1…\n$ urbanizacion            <dbl> 69.1, 61.8, 62.9, 68.6, 54.5, 32.3, 57.6, 52.1…\n$ gasto_salud             <dbl> 8.3, 7.6, 4.5, 5.5, 4.3, 4.6, 8.3, 6.9, 4.8, 6…\n$ inflacion               <dbl> 9.4, 9.2, 10.3, 14.7, 12.2, 11.8, 11.2, 23.4, …\n$ desempleo               <dbl> 5.9, 10.0, 7.2, 13.1, 12.7, 9.7, 9.5, 14.0, 9.…\n$ inversion_extranjera    <dbl> 2.4, 4.8, 2.5, 4.1, 2.3, 2.3, 5.5, 3.6, 5.2, 1…\n$ indice_gobierno_digital <dbl> 0.38, 0.78, 0.13, 0.49, 0.52, 0.33, 0.57, 0.33…\n$ crecimiento_alto        <chr> \"si\", \"si\", \"no\", \"no\", \"no\", \"si\", \"no\", \"no\"…\n```\n\n\n:::\n:::\n\n\n**Variable objetivo:** `crecimiento_alto` (sí/no) - ¿El país tuvo crecimiento del PIB mayor o igual a 3%?\n:::\n\n## Descripción de las variables\n\n:::{style=\"margin-top: 30px; font-size: 28px;\"}\n\n| Variable | Descripción | Tipo |\n|----------|-------------|------|\n| `crecimiento_alto` | PIB creció ≥ 3% (sí/no) | Categórica |\n| `gasto_educacion` | Gasto en educación (% del PIB) | Numérica |\n| `acceso_internet` | Acceso a internet (% de la población) | Numérica |\n| `urbanizacion` | Población urbana (% del total) | Numérica |\n| `gasto_salud` | Gasto en salud (% del PIB) | Numérica |\n| `inflacion` | Tasa de inflación anual (%) | Numérica |\n| `desempleo` | Tasa de desempleo (%) | Numérica |\n| `inversion_extranjera` | IED (% del PIB) | Numérica |\n| `indice_gobierno_digital` | Índice de gobierno digital (0-1) | Numérica |\n| `pais` | Nombre del país | Categórica |\n| `continente` | Continente | Categórica |\n\n:::\n\n## Estadísticas descriptivas\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\nAntes de modelar, conviene ver [cómo se distribuyen las variables]{.alert} y si difieren entre los grupos de `crecimiento_alto`. Mostramos acá [3 de los 8 predictores]{.alert}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Resumen rápido de las variables numéricas\ndatos |> select(where(is.numeric)) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n gasto_educacion acceso_internet  urbanizacion    gasto_salud   \n Min.   :2.100   Min.   : 5.00   Min.   :16.40   Min.   :3.200  \n 1st Qu.:4.400   1st Qu.:46.60   1st Qu.:44.70   1st Qu.:5.800  \n Median :5.000   Median :57.50   Median :58.10   Median :6.700  \n Mean   :5.027   Mean   :57.52   Mean   :58.42   Mean   :6.631  \n 3rd Qu.:5.600   3rd Qu.:68.35   3rd Qu.:73.15   3rd Qu.:7.450  \n Max.   :8.000   Max.   :99.00   Max.   :97.60   Max.   :9.500  \n   inflacion       desempleo      inversion_extranjera indice_gobierno_digital\n Min.   : 5.20   Min.   : 1.500   Min.   :0.200        Min.   :0.0800         \n 1st Qu.: 9.35   1st Qu.: 6.700   1st Qu.:3.050        1st Qu.:0.4050         \n Median :11.70   Median : 8.400   Median :4.200        Median :0.5200         \n Mean   :12.73   Mean   : 8.434   Mean   :4.079        Mean   :0.5136         \n 3rd Qu.:14.70   3rd Qu.:10.100   3rd Qu.:5.100        3rd Qu.:0.6350         \n Max.   :37.40   Max.   :16.100   Max.   :7.400        Max.   :0.9600         \n```\n\n\n:::\n\n```{.r .cell-code}\n# Medias por nivel de crecimiento (3 predictores ilustrativos)\ndatos |>\n  group_by(crecimiento_alto) |>\n  summarise(\n    educacion_media     = mean(gasto_educacion),\n    internet_medio      = mean(acceso_internet),\n    urbanizacion_media  = mean(urbanizacion)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  crecimiento_alto educacion_media internet_medio urbanizacion_media\n  <chr>                      <dbl>          <dbl>              <dbl>\n1 no                          4.75           51.8               54.8\n2 si                          5.33           63.7               62.3\n```\n\n\n:::\n:::\n\n\n[Detalle por variable en Apéndice 2; relaciones con el objetivo en Apéndice 3; visualizaciones en Apéndice 4]{.alert}\n:::\n\n## Ejercicio 1: Exploración {#sec:exercise01}\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n**Tarea:** Exploren una de las variables que [no]{.alert} mostramos en la diapositiva anterior.\n\n1. ¿Cuántas observaciones? ¿Hay valores faltantes?\n2. ¿Cómo se distribuye la variable objetivo `crecimiento_alto`?\n3. Elijan [una]{.alert} de estas preguntas y respóndanla con una [comparación numérica]{.alert} (el gráfico es opcional):\n    - Elijan [una]{.alert} de `inflacion`, `desempleo`, `inversion_extranjera` o `indice_gobierno_digital` y comparen su media (o mediana) entre países con `crecimiento_alto = \"si\"` y `\"no\"`. ¿La diferencia parece grande?\n    - ¿Están altamente correlacionados `acceso_internet` y `urbanizacion`? Si lo están, podríamos no necesitar a los dos en el modelo\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Código para empezar\ndim(datos)\ndatos |> count(crecimiento_alto) |> mutate(prop = n / sum(n))\n\n# Ejemplo para la primera pregunta: media de gasto_salud por grupo\ndatos |>\n  group_by(crecimiento_alto) |>\n  summarise(media_gasto_salud = mean(gasto_salud))\n\n# Ejemplo para la segunda pregunta: correlación entre dos predictores\ncor(datos$acceso_internet, datos$urbanizacion)\n```\n:::\n\n\n[Tómense 5-10 minutos]{.alert}\n\n[[App 1: exploración inicial]{.button}](#sec:appendix01) · [[App 2: ¿media o mediana?]{.button}](#sec:appendix02) · [[App 3: comparación numérica por grupo]{.button}](#sec:appendix03) · [[App 4: versión visual (opcional)]{.button}](#sec:appendix04)\n:::\n\n# Parte 2: Feature engineering {background-color=\"#2d4563\"}\n\n## Preparar los datos\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n\nConvertimos la variable objetivo a factor y descartamos las columnas que no usaremos como predictores. [`pais`]{.alert} tiene 179 valores únicos y [`continente`]{.alert} la dejamos fuera para quedarnos con predictores numéricos, igual que en el lab 1.\n\nCreamos un nuevo objeto [`datos_modelo`]{.alert} y mantenemos `datos` intacto para los apéndices y la exploración:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Frame listo para modelar (datos sigue intacto con pais y continente)\ndatos_modelo <- datos |>\n  mutate(crecimiento_alto = factor(crecimiento_alto, levels = c(\"no\", \"si\"))) |>\n  select(-pais, -continente)\n\n# Verificar\nglimpse(datos_modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 179\nColumns: 9\n$ gasto_educacion         <dbl> 5.7, 4.0, 3.2, 5.0, 4.6, 4.8, 4.6, 4.3, 5.9, 5…\n$ acceso_internet         <dbl> 50.2, 48.0, 34.3, 46.2, 62.5, 66.0, 55.5, 39.1…\n$ urbanizacion            <dbl> 69.1, 61.8, 62.9, 68.6, 54.5, 32.3, 57.6, 52.1…\n$ gasto_salud             <dbl> 8.3, 7.6, 4.5, 5.5, 4.3, 4.6, 8.3, 6.9, 4.8, 6…\n$ inflacion               <dbl> 9.4, 9.2, 10.3, 14.7, 12.2, 11.8, 11.2, 23.4, …\n$ desempleo               <dbl> 5.9, 10.0, 7.2, 13.1, 12.7, 9.7, 9.5, 14.0, 9.…\n$ inversion_extranjera    <dbl> 2.4, 4.8, 2.5, 4.1, 2.3, 2.3, 5.5, 3.6, 5.2, 1…\n$ indice_gobierno_digital <dbl> 0.38, 0.78, 0.13, 0.49, 0.52, 0.33, 0.57, 0.33…\n$ crecimiento_alto        <fct> si, si, no, no, no, si, no, no, si, no, no, no…\n```\n\n\n:::\n:::\n\n\n[Mantenemos el orden `c(\"no\", \"si\")` para que `\"si\"` sea la clase positiva. Más adelante usaremos `event_level = \"second\"`]{.alert}\n:::\n\n## Crear nuevas variables\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\nEl [feature engineering]{.alert} puede mejorar el rendimiento del modelo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Crear nuevas variables sobre el frame que va al modelo\ndatos_modelo <- datos_modelo |>\n  mutate(\n    # Grupos de urbanización (rural, mixto, urbano)\n    grupo_urbanizacion = cut(urbanizacion,\n                             breaks = c(0, 50, 75, 100),\n                             labels = c(\"rural\", \"mixto\", \"urbano\"),\n                             include.lowest = TRUE),\n\n    # Intensidad fiscal social: cuánto del PIB va a salud + educación\n    gasto_social = gasto_educacion + gasto_salud,\n\n    # Indicador de alto desempleo (lo usaremos como ejemplo más adelante)\n    alto_desempleo = factor(if_else(desempleo > 7, \"alto\", \"bajo\"))\n  )\n\n# Ver las nuevas variables\ndatos_modelo |> select(grupo_urbanizacion, gasto_social, alto_desempleo) |> head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  grupo_urbanizacion gasto_social alto_desempleo\n  <fct>                     <dbl> <fct>         \n1 mixto                      14   bajo          \n2 mixto                      11.6 alto          \n3 mixto                       7.7 alto          \n4 mixto                      10.5 alto          \n5 mixto                       8.9 alto          \n6 rural                       9.4 alto          \n```\n\n\n:::\n:::\n\n:::\n\n## Ejercicio 2: Crear un feature {#sec:exercise02}\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\n**Tarea:** Elijan [una]{.alert} variable derivada y créenla\n\nOpciones sugeridas (elijan la que más les interese). Entre paréntesis, la variable base:\n\n- [Acceso a internet por terciles]{.alert}: bajo, medio, alto (`acceso_internet`)\n- [Gasto en educación alto]{.alert}: por encima de la mediana del dataset (`gasto_educacion`)\n- [Inflación alta]{.alert}: tasa mayor a 15% (`inflacion`)\n- [Apertura financiera]{.alert}: IED por encima de la mediana (`inversion_extranjera`)\n- [Otro que se les ocurra]{.alert} (¡la creatividad es bienvenida!)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Ejemplo: crear variable internet_grupos por terciles\ndatos_modelo <- datos_modelo |>\n  mutate(\n    internet_grupos = cut(acceso_internet,\n                          breaks = quantile(acceso_internet, c(0, 1/3, 2/3, 1)),\n                          labels = c(\"bajo\", \"medio\", \"alto\"),\n                          include.lowest = TRUE)\n  )\n```\n:::\n\n\n[¡Tómense 3-5 minutos!]{.alert}\n\n[[Más ejemplos en el Apéndice 5]{.button}](#sec:appendix05)\n:::\n\n## Dividir los datos\n\n:::{style=\"margin-top: 30px; font-size: 23px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fijar semilla\nset.seed(2026)\n\n# Dividir datos (usando el frame con la variable objetivo como factor)\ndatos_split <- initial_split(datos_modelo, prop = 0.75, strata = crecimiento_alto)\ndatos_train <- training(datos_split)\ndatos_test <- testing(datos_split)\n\n# Crear folds para validación cruzada\nfolds <- vfold_cv(datos_train, v = 5, strata = crecimiento_alto)\n\ncat(\"Train:\", nrow(datos_train), \"| Test:\", nrow(datos_test))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrain: 133 | Test: 46\n```\n\n\n:::\n:::\n\n\n- `initial_split()`: Divide el dataset en train/test\n- `training()` y `testing()`: Extraen los datasets de train y test\n- `vfold_cv()`: Crea folds para validación cruzada (5 folds, estratificados por `crecimiento_alto`)\n\nCon 179 países y 5 folds, cada partición tiene pocos países en validación. Es suficiente para entrenar, pero las métricas tendrán [más ruido]{.alert}\n:::\n\n# Parte 3: Comparación de modelos {background-color=\"#2d4563\"}\n\n## Definir los modelos a comparar\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\nVamos a comparar dos modelos de naturaleza distinta: uno lineal y uno no lineal\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Regresión logística (lineal)\nmodelo_logistico <- logistic_reg() |>\n  set_engine(\"glm\") |>\n  set_mode(\"classification\")\n\n# 2. Árbol de decisión (no lineal, captura interacciones automáticamente)\nmodelo_arbol <- decision_tree() |>\n  set_engine(\"rpart\") |>\n  set_mode(\"classification\")\n```\n:::\n\n\nLa [misma sintaxis]{.alert} sirve para ambos: esa es la ventaja de `parsnip`. Otros motores (`kknn`, `ranger`, `xgboost`) funcionan igual cambiando solo `set_engine()` \n\nUna vez más, la lista de modelos disponibles está en <https://www.tidymodels.org/find/parsnip/>\n:::\n\n## Crear una fórmula\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\nDecidamos qué variables usar:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fórmula con las 8 variables numéricas originales\nformula_basica <- crecimiento_alto ~ gasto_educacion + acceso_internet +\n                                     urbanizacion + gasto_salud + inflacion +\n                                     desempleo + inversion_extranjera +\n                                     indice_gobierno_digital\n```\n:::\n\n\nMás adelante añadiremos una variable derivada para ver si mejora el ajuste\n:::\n\n## Evaluar el modelo logístico\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n\nValidación cruzada en 5 folds y resumen de métricas:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Las tres métricas juntas en un objeto que vamos a reusar todo el lab\nmis_metricas <- metric_set(precision, recall, roc_auc)\n\neval_logistico <- fit_resamples(\n  modelo_logistico, formula_basica,\n  resamples = folds,\n  metrics = mis_metricas,\n  control = control_resamples(event_level = \"second\")   # \"si\" es la clase positiva\n) |>\n  collect_metrics() |>\n  mutate(modelo = \"Logístico\")\n\neval_logistico\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  .metric   .estimator  mean     n std_err .config         modelo   \n  <chr>     <chr>      <dbl> <int>   <dbl> <chr>           <chr>    \n1 precision binary     0.768     5  0.0714 pre0_mod0_post0 Logístico\n2 recall    binary     0.782     5  0.0559 pre0_mod0_post0 Logístico\n3 roc_auc   binary     0.846     5  0.0512 pre0_mod0_post0 Logístico\n```\n\n\n:::\n:::\n\n\n- `fit_resamples()` ajusta el modelo en cada fold de la validación cruzada\n- [`metric_set()`]{.alert} junta varias métricas en un solo objeto. Lo guardamos en `mis_metricas` y lo reusamos en cada evaluación\n- `collect_metrics()` devuelve la media y el error estándar de cada métrica entre folds\n- `control = control_resamples(event_level = \"second\")` indica que la clase positiva es [`\"si\"`]{.alert}\n- Usamos [precision, recall y roc_auc]{.alert} en lugar de accuracy: con clases desbalanceadas, la accuracy puede ser engañosa\n- En el resultado, [`.metric`]{.alert} guarda el nombre de cada métrica (`precision`, `recall`, `roc_auc`) y `mean` y `std_err` \n:::\n\n## Evaluar el árbol y comparar {#sec:evaluar-todos}\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# El mismo bloque que antes, cambiando modelo_logistico → modelo_arbol\neval_arbol <- fit_resamples(\n  modelo_arbol, formula_basica,\n  resamples = folds,\n  metrics = mis_metricas,\n  control = control_resamples(event_level = \"second\")\n) |>\n  collect_metrics() |>\n  mutate(modelo = \"Árbol\")\n\n# Combinar y mostrar la comparación\nresultados <- bind_rows(eval_logistico, eval_arbol)\n\n# Una fila por modelo y métrica, ordenadas para comparar de a pares\nresultados |>\n  select(modelo, .metric, mean, std_err) |>\n  arrange(.metric, modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  modelo    .metric    mean std_err\n  <chr>     <chr>     <dbl>   <dbl>\n1 Logístico precision 0.768  0.0714\n2 Árbol     precision 0.686  0.0453\n3 Logístico recall    0.782  0.0559\n4 Árbol     recall    0.706  0.0813\n5 Logístico roc_auc   0.846  0.0512\n6 Árbol     roc_auc   0.717  0.0501\n```\n\n\n:::\n:::\n\n\n[Versión visual de esta comparación (barras con error estándar) en [[Apéndice 7]{.button}](#sec:appendix07)]{.alert}\n\n[Para discutir:]{.alert} las diferencias entre los dos modelos son chicas y sus errores estándar se solapan. ¿Pueden afirmar que un modelo es [claramente mejor]{.alert}? ¿Cuál reportarían y por qué?\n:::\n\n## ¿Qué pasa si extendemos la fórmula?\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n\nAntes de pedirles que prueben su propia variable, miremos un ejemplo trabajado. Reemplazamos [`desempleo`]{.alert} (continuo) por [`alto_desempleo`]{.alert} (binario, la creamos antes en la demo) y re-evaluamos el modelo logístico:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fórmula extendida con un feature derivado\nformula_ext <- crecimiento_alto ~ acceso_internet + gasto_educacion + urbanizacion + gasto_salud + inflacion +\n                                  alto_desempleo + inversion_extranjera + indice_gobierno_digital\n\n# Logístico con formula_ext\neval_log_ext <- fit_resamples(modelo_logistico, formula_ext, resamples = folds,\n  metrics = mis_metricas,\n  control = control_resamples(event_level = \"second\")) |>\n  collect_metrics() |> mutate(modelo = \"Logístico (ext)\")\n\n# Comparar el logístico básico vs. el extendido\nbind_rows(eval_logistico, eval_log_ext) |>\n  select(modelo, .metric, mean, std_err) |>\n  arrange(.metric, modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  modelo          .metric    mean std_err\n  <chr>           <chr>     <dbl>   <dbl>\n1 Logístico       precision 0.768  0.0714\n2 Logístico (ext) precision 0.787  0.0640\n3 Logístico       recall    0.782  0.0559\n4 Logístico (ext) recall    0.799  0.0514\n5 Logístico       roc_auc   0.846  0.0512\n6 Logístico (ext) roc_auc   0.850  0.0580\n```\n\n\n:::\n:::\n\n\n- En este ejemplo, [`alto_desempleo`]{.alert} cambia las métricas del logístico apenas unas milésimas\n- Una lección: no todo feature engineering mejora el modelo. Cuando el predictor original ya capta la información, reemplazarlo por un recorte categórico es redundante. Hay que [medirlo]{.alert}, no asumirlo\n:::\n\n## Ejercicio 3: ¿Ayuda el feature engineering? {#sec:exercise03}\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n**Tarea:** Agreguen un feature a la fórmula y re-evalúen: la variable que crearon en el [Ejercicio 2]{.alert}, o una [interacción]{.alert} entre dos variables (como en el ejemplo)\n\n1. ¿Mejora la regresión logística? ¿Y el árbol?\n2. ¿Cuál de los dos modelos es más sensible al feature nuevo?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Ejemplo: una interacción entre dos variables que se refuerzan\n# (gobierno digital y acceso a internet). En una fórmula se escribe con \":\"\nformula_estudiante <- crecimiento_alto ~ gasto_educacion + acceso_internet +\n                                         urbanizacion + gasto_salud + inflacion +\n                                         desempleo + inversion_extranjera +\n                                         indice_gobierno_digital +\n                                         indice_gobierno_digital:acceso_internet\n\n# Repetir el mismo bloque, ahora con formula_estudiante\neval_log_est <- fit_resamples(modelo_logistico, formula_estudiante, resamples = folds,\n  metrics = mis_metricas,\n  control = control_resamples(event_level = \"second\")) |>\n  collect_metrics() |> mutate(modelo = \"Logístico (estudiante)\")\n\n# Lo mismo cambiando modelo_logistico → modelo_arbol\neval_arb_est <- fit_resamples(modelo_arbol, formula_estudiante, resamples = folds,\n  metrics = mis_metricas,\n  control = control_resamples(event_level = \"second\")) |>\n  collect_metrics() |> mutate(modelo = \"Árbol (estudiante)\")\n\n# Comparar los 4 modelos: básicos + el suyo\nbind_rows(eval_logistico, eval_log_est, eval_arbol, eval_arb_est) |>\n  filter(.metric == \"roc_auc\") |> select(modelo, mean, std_err)\n```\n:::\n\n\n[¡Tómense 5 minutos!]{.alert}\n\n[[Ir al Apéndice 6]{.button}](#sec:appendix06)\n:::\n\n## Modelo final en datos de test\n\n:::{style=\"margin-top: 30px; font-size: 21px;\"}\n\nUna vez elegido el mejor modelo por validación cruzada, lo entrenamos con todos los datos de train y lo evaluamos [una sola vez]{.alert} en test (los datos que el modelo nunca vio):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Entrenar el modelo elegido con todos los datos de train\najuste_final <- modelo_logistico |>\n  fit(formula_ext, data = datos_train)\n\n# augment() junta predicciones (clases + probabilidades) con los datos originales\n# en una sola línea. Equivale a hacer dos predict() + bind_cols().\npred_test <- ajuste_final |> augment(datos_test)\n\n# Métricas finales: el mismo mis_metricas de la validación cruzada\npred_test |> mis_metricas(truth = crecimiento_alto, estimate = .pred_class, .pred_si, event_level = \"second\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric   .estimator .estimate\n  <chr>     <chr>          <dbl>\n1 precision binary         0.783\n2 recall    binary         0.818\n3 roc_auc   binary         0.888\n```\n\n\n:::\n:::\n\n\n- [`augment()`]{.alert} toma un modelo ajustado y un conjunto de datos, y añade las predicciones como columnas nuevas: `.pred_class` (clase predicha), `.pred_no`, `.pred_si` (probabilidades)\n- El prefijo `.` es la convención de tidymodels para columnas que el paquete crea por ustedes\n- Reemplaza dos llamadas a `predict()` y dos `bind_cols()` por una sola línea\n- [`mis_metricas`]{.alert} devuelve las tres métricas en una sola tabla. Necesita las dos cosas: `estimate = .pred_class` para precision y recall, y `.pred_si` (la probabilidad) para el roc_auc\n:::\n\n## Tarea para casa\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\nHay una [tarea para las dos sesiones]{.alert} con preguntas prácticas que aplican todo lo que vimos hoy.\n\n- Página de [Laboratorios](https://danilofreire.github.io/introduccion-ia-ucu/laboratorios.html) del sitio del curso\n- [Tarea 1](https://danilofreire.github.io/introduccion-ia-ucu/clases/dia-01/tarea-01.html)\n- [Respuestas Tarea 1](https://danilofreire.github.io/introduccion-ia-ucu/clases/dia-01/tarea-01-respuestas.html)\n- [Tarea 2](https://danilofreire.github.io/introduccion-ia-ucu/clases/dia-01/tarea-02.html)\n- [Respuestas Tarea 2](https://danilofreire.github.io/introduccion-ia-ucu/clases/dia-01/tarea-02-respuestas.html)\n\n<br>\n\n[Las respuestas ya están disponibles para que verifiquen su trabajo]{.alert} 😉\n:::\n\n# Cierre del Día 1 {background-color=\"#2d4563\"}\n\n## Lo que cubrimos hoy\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n:::{.columns}\n:::{.column width=50%}\n**Sesión 1.1: ¿Qué es la IA?**\n\n- Definición y tipos de IA\n- Historia: de Turing a GPT\n- Tipos de aprendizaje automático\n- Ética básica\n\n**Sesión 1.2: Fundamentos de ML**\n\n- Flujo de trabajo de ML\n- División y validación\n- Sobreajuste y sesgo-varianza\n- Métricas de evaluación\n:::\n\n:::{.column width=50%}\n**Sesión 1.3: Laboratorio 1**\n\n- Ecosistema tidymodels\n- Primer modelo de clasificación\n- Matriz de confusión y métricas\n\n**Sesión 1.4: Laboratorio 2**\n\n- Exploración extendida con el mismo dataset\n- Feature engineering básico\n- Logístico vs. árbol con validación cruzada\n- Tarea 2 disponible en la página de laboratorios\n:::\n:::\n:::\n\n## Para mañana\n\n:::{style=\"margin-top: 40px; font-size: 26px;\"}\n\n**Día 2: Aprendizaje supervisado**\n\n- Sesión 2.1: Métodos de clasificación\n    - Regresión logística en detalle, árboles de decisión, Random Forests\n\n- Sesión 2.2: Regresión y predicción\n    - Regularización (LASSO, Ridge, Elastic Net) e ingeniería de variables\n\n- Sesiones 2.3 y 2.4: Laboratorios con datos de Latinobarómetro\n\n**Para profundizar (todo gratis):** [Tidy Modeling with R](https://www.tmwr.org/) -- [R for Data Science](https://r4ds.hadley.nz/) -- [Get Started with tidymodels](https://www.tidymodels.org/start/)\n\n[¡Descansen y vengan con energía mañana!]{.alert} 😄\n:::\n\n# Fin del Día 1 🥳 {background-color=\"#2d4563\"}\n\n# Apéndices {background-color=\"#2d4563\"}\n\n## Apéndice 1: Exploración inicial {#sec:appendix01}\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Dimensiones\ndim(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 179  11\n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Distribución de la variable objetivo\ndatos |>\n  count(crecimiento_alto) |>\n  mutate(prop = round(n / sum(n), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  crecimiento_alto     n  prop\n  <chr>            <int> <dbl>\n1 no                  93  0.52\n2 si                  86  0.48\n```\n\n\n:::\n\n```{.r .cell-code}\n# 3. Valores faltantes por variable\ncolSums(is.na(datos))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   pais              continente         gasto_educacion \n                      0                       0                       0 \n        acceso_internet            urbanizacion             gasto_salud \n                      0                       0                       0 \n              inflacion               desempleo    inversion_extranjera \n                      0                       0                       0 \nindice_gobierno_digital        crecimiento_alto \n                      0                       0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 4. Resumen de variables numéricas\ndatos |>\n  select(where(is.numeric)) |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n gasto_educacion acceso_internet  urbanizacion    gasto_salud   \n Min.   :2.100   Min.   : 5.00   Min.   :16.40   Min.   :3.200  \n 1st Qu.:4.400   1st Qu.:46.60   1st Qu.:44.70   1st Qu.:5.800  \n Median :5.000   Median :57.50   Median :58.10   Median :6.700  \n Mean   :5.027   Mean   :57.52   Mean   :58.42   Mean   :6.631  \n 3rd Qu.:5.600   3rd Qu.:68.35   3rd Qu.:73.15   3rd Qu.:7.450  \n Max.   :8.000   Max.   :99.00   Max.   :97.60   Max.   :9.500  \n   inflacion       desempleo      inversion_extranjera indice_gobierno_digital\n Min.   : 5.20   Min.   : 1.500   Min.   :0.200        Min.   :0.0800         \n 1st Qu.: 9.35   1st Qu.: 6.700   1st Qu.:3.050        1st Qu.:0.4050         \n Median :11.70   Median : 8.400   Median :4.200        Median :0.5200         \n Mean   :12.73   Mean   : 8.434   Mean   :4.079        Mean   :0.5136         \n 3rd Qu.:14.70   3rd Qu.:10.100   3rd Qu.:5.100        3rd Qu.:0.6350         \n Max.   :37.40   Max.   :16.100   Max.   :7.400        Max.   :0.9600         \n```\n\n\n:::\n:::\n\n\n[[Volver al Ejercicio 1]{.button}](#sec:exercise01)\n:::\n\n## Apéndice 2: Una variable a fondo {#sec:appendix02}\n\n:::{style=\"margin-top: 20px; font-size: 20px;\"}\n\nEl Ejercicio 1 les pide comparar la [media o la mediana]{.alert}. ¿Cuándo conviene usar la mediana? Cuando la variable tiene cola larga y la media deja de representarla bien. Tomemos [`inflacion`]{.alert}: tiene cola larga, así que la media (≈ 12.7) es mayor que la mediana (≈ 11.7), y hay países con inflación de hasta ~37% que estiran el promedio:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estadísticas detalladas\nsummary(datos$inflacion)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   5.20    9.35   11.70   12.73   14.70   37.40 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Histograma (muestra la cola larga)\nggplot(datos, aes(x = inflacion)) +\n  geom_histogram(bins = 30, fill = \"#2d4563\") +\n  labs(x = \"Inflación anual (%)\", y = \"Países\")\n```\n\n::: {.cell-output-display}\n![](04-laboratorio-02_files/figure-revealjs/appendix02univar-1.png){fig-align='center' width=3000}\n:::\n\n```{.r .cell-code}\n# Densidad por grupo (¿separa crecimiento alto de bajo?)\nggplot(datos, aes(x = inflacion, fill = crecimiento_alto)) +\n  geom_density(alpha = 0.5) +\n  scale_fill_manual(values = c(\"#e74c3c\", \"#27ae60\")) +\n  labs(x = \"Inflación anual (%)\")\n```\n\n::: {.cell-output-display}\n![](04-laboratorio-02_files/figure-revealjs/appendix02univar-2.png){fig-align='center' width=3000}\n:::\n:::\n\n\n[Cambien el nombre de la variable (`gasto_salud`, `desempleo`, `indice_gobierno_digital`, etc.) para repetir el análisis con otra. La mayoría de los predictores son casi simétricos; `inflacion` es la excepción]{.alert}\n\n[[Volver al Ejercicio 1]{.button}](#sec:exercise01)\n:::\n\n## Apéndice 3: Predictores vs. objetivo {#sec:appendix03}\n\n:::{style=\"margin-top: 20px; font-size: 20px;\"}\n\nEsta es la [comparación numérica]{.alert} que pide el ejercicio: las medias por grupo son la pista más rápida, porque si difieren mucho, la variable probablemente ayudará al modelo. Acá las [5 que no mostramos en el cuerpo]{.alert}:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Medias por grupo de las 4 variables no mostradas en el cuerpo\ndatos |>\n  group_by(crecimiento_alto) |>\n  summarise(\n    salud         = mean(gasto_salud),\n    inflacion     = mean(inflacion),\n    desempleo     = mean(desempleo),\n    ied           = mean(inversion_extranjera),\n    gob_digital   = mean(indice_gobierno_digital)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  crecimiento_alto salud inflacion desempleo   ied gob_digital\n  <chr>            <dbl>     <dbl>     <dbl> <dbl>       <dbl>\n1 no                6.40      14.7      9.56  3.50       0.438\n2 si                6.88      10.6      7.22  4.70       0.595\n```\n\n\n:::\n\n```{.r .cell-code}\n# Correlación entre todos los predictores numéricos (¿hay pares redundantes?)\ndatos |>\n  select(where(is.numeric)) |>\n  cor() |>\n  round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        gasto_educacion acceso_internet urbanizacion\ngasto_educacion                    1.00            0.07         0.24\nacceso_internet                    0.07            1.00         0.10\nurbanizacion                       0.24            0.10         1.00\ngasto_salud                        0.26            0.09         0.21\ninflacion                         -0.08           -0.05        -0.13\ndesempleo                         -0.22           -0.13        -0.28\ninversion_extranjera               0.21            0.17         0.14\nindice_gobierno_digital            0.18            0.20         0.21\n                        gasto_salud inflacion desempleo inversion_extranjera\ngasto_educacion                0.26     -0.08     -0.22                 0.21\nacceso_internet                0.09     -0.05     -0.13                 0.17\nurbanizacion                   0.21     -0.13     -0.28                 0.14\ngasto_salud                    1.00     -0.17     -0.15                 0.09\ninflacion                     -0.17      1.00      0.18                -0.18\ndesempleo                     -0.15      0.18      1.00                -0.18\ninversion_extranjera           0.09     -0.18     -0.18                 1.00\nindice_gobierno_digital        0.32     -0.28     -0.30                 0.39\n                        indice_gobierno_digital\ngasto_educacion                            0.18\nacceso_internet                            0.20\nurbanizacion                               0.21\ngasto_salud                                0.32\ninflacion                                 -0.28\ndesempleo                                 -0.30\ninversion_extranjera                       0.39\nindice_gobierno_digital                    1.00\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test formal para una variable concreta\nt.test(indice_gobierno_digital ~ crecimiento_alto, data = datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  indice_gobierno_digital by crecimiento_alto\nt = -6.8831, df = 175.49, p-value = 9.985e-11\nalternative hypothesis: true difference in means between group no and group si is not equal to 0\n95 percent confidence interval:\n -0.2023819 -0.1121868\nsample estimates:\nmean in group no mean in group si \n       0.4380645        0.5953488 \n```\n\n\n:::\n:::\n\n\n[[Volver al Ejercicio 1]{.button}](#sec:exercise01)\n:::\n\n## Apéndice 4: Boxplots de las 4 variables no mostradas {#sec:appendix04}\n\n:::{style=\"margin-top: 20px; font-size: 20px;\"}\n\nVersión [visual (opcional)]{.alert} de la primera pregunta: las mismas diferencias de medias del Apéndice 3, ahora como boxplots. ¿Alguna de las cuatro variables que [no]{.alert} aparecen en las estadísticas descriptivas separa bien `crecimiento_alto`?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndatos |>\n  select(crecimiento_alto, gasto_salud, desempleo, inversion_extranjera, indice_gobierno_digital) |>\n  pivot_longer(-crecimiento_alto, names_to = \"variable\", values_to = \"valor\") |>\n  ggplot(aes(x = crecimiento_alto, y = valor, fill = crecimiento_alto)) +\n  geom_boxplot(alpha = 0.7) +\n  facet_wrap(~variable, scales = \"free_y\") +\n  scale_fill_manual(values = c(\"#e74c3c\", \"#27ae60\")) +\n  labs(title = \"Las 4 variables no mostradas, por nivel de crecimiento\", x = NULL, y = NULL) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](04-laboratorio-02_files/figure-revealjs/appendix04-box-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n[[Volver al Ejercicio 1]{.button}](#sec:exercise01)\n:::\n\n## Apéndice 4 (cont.): Acceso a internet vs. urbanización\n\n:::{style=\"margin-top: 20px; font-size: 20px;\"}\n\nVersión [visual (opcional)]{.alert} de la segunda pregunta. Si la nube de puntos cae cerca de una recta, los dos predictores capturan información parecida (colinealidad):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(datos, aes(x = urbanizacion, y = acceso_internet, color = crecimiento_alto)) +\n  geom_point(alpha = 0.6) +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  scale_color_manual(values = c(\"#e74c3c\", \"#27ae60\")) +\n  labs(x = \"Urbanización (%)\", y = \"Acceso a internet (%)\")\n```\n\n::: {.cell-output-display}\n![](04-laboratorio-02_files/figure-revealjs/appendix04c-1.png){fig-align='center' width=3000}\n:::\n\n```{.r .cell-code}\n# La correlación numérica complementa el gráfico\ncor(datos$urbanizacion, datos$acceso_internet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1032229\n```\n\n\n:::\n:::\n\n\n[[Volver al Ejercicio 1]{.button}](#sec:exercise01)\n:::\n\n## Apéndice 5: Crear más features {#sec:appendix05}\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Una posible solución para cada una de las cuatro opciones sugeridas\ndatos_modelo <- datos_modelo |>\n  mutate(\n    # 1. Gasto en educación alto (gasto_educacion)\n    educacion_alta = if_else(gasto_educacion > median(gasto_educacion), \"alta\", \"baja\"),\n\n    # 2. Acceso a internet por terciles (acceso_internet)\n    internet_grupos = cut(acceso_internet,\n                          breaks = quantile(acceso_internet, c(0, 1/3, 2/3, 1)),\n                          labels = c(\"bajo\", \"medio\", \"alto\"),\n                          include.lowest = TRUE),\n\n    # 3. Inflación alta (inflacion)\n    inflacion_alta = if_else(inflacion > 15, \"si\", \"no\"),\n\n    # 4. Apertura financiera: IED por encima de la mediana (inversion_extranjera)\n    apertura_financiera = if_else(inversion_extranjera > median(inversion_extranjera), \"alta\", \"baja\")\n  )\n\n# Verificar las nuevas variables\ndatos_modelo |> count(educacion_alta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  educacion_alta     n\n  <chr>          <int>\n1 alta              87\n2 baja              92\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos_modelo |> count(internet_grupos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  internet_grupos     n\n  <fct>           <int>\n1 bajo               60\n2 medio              59\n3 alto               60\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos_modelo |> count(inflacion_alta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  inflacion_alta     n\n  <chr>          <int>\n1 no               140\n2 si                39\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos_modelo |> count(apertura_financiera)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  apertura_financiera     n\n  <chr>               <int>\n1 alta                   83\n2 baja                   96\n```\n\n\n:::\n:::\n\n\n[[Volver al Ejercicio 2]{.button}](#sec:exercise02)\n:::\n\n## Apéndice 6: ¿Ayuda el feature engineering? {#sec:appendix06}\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Una interacción no necesita una columna nueva: se agrega a la fórmula con \":\".\n# Probamos indice_gobierno_digital × acceso_internet (dos variables que se refuerzan)\nformula_int <- crecimiento_alto ~ gasto_educacion + acceso_internet +\n                                  urbanizacion + gasto_salud + inflacion +\n                                  desempleo + inversion_extranjera +\n                                  indice_gobierno_digital +\n                                  indice_gobierno_digital:acceso_internet\n\n# Evaluar el logístico (reusamos los mismos folds del cuerpo del lab)\neval_log_int <- fit_resamples(\n  modelo_logistico, formula_int, resamples = folds,\n  metrics = mis_metricas,\n  control = control_resamples(event_level = \"second\")\n) |>\n  collect_metrics() |> mutate(modelo = \"Logístico (interacción)\")\n\n# Evaluar el árbol con la misma fórmula\neval_arb_int <- fit_resamples(\n  modelo_arbol, formula_int, resamples = folds,\n  metrics = mis_metricas,\n  control = control_resamples(event_level = \"second\")\n) |>\n  collect_metrics() |> mutate(modelo = \"Árbol (interacción)\")\n\nbind_rows(eval_logistico, eval_log_int, eval_arbol, eval_arb_int) |>\n  filter(.metric == \"roc_auc\") |>\n  select(modelo, mean, std_err) |>\n  arrange(desc(mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  modelo                   mean std_err\n  <chr>                   <dbl>   <dbl>\n1 Logístico (interacción) 0.851  0.0483\n2 Logístico               0.846  0.0512\n3 Árbol (interacción)     0.738  0.0687\n4 Árbol                   0.717  0.0501\n```\n\n\n:::\n:::\n\n\nLa interacción `indice_gobierno_digital:acceso_internet` mejora un poco el ROC-AUC de [ambos modelos]{.alert}: capta el efecto conjunto de dos variables que se refuerzan, algo que las variables por separado no expresan (la mejora es chica y está dentro del error estándar, así que no conviene sobre-interpretarla). El contraste con `alto_desempleo`, que [no ayudó]{.alert}, deja la moraleja: reemplazar una variable continua por su versión discretizada suele ser redundante, mientras que una [interacción]{.alert} o una transformación no lineal sí puede agregar información nueva\n\n[[Volver al Ejercicio 3]{.button}](#sec:exercise03)\n:::\n\n## Apéndice 7: Visualizar la comparación de modelos {#sec:appendix07}\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\nUna alternativa visual al cuadro de comparación:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresultados |>\n  ggplot(aes(x = modelo, y = mean, fill = modelo)) +\n  geom_col(alpha = 0.8) +\n  geom_errorbar(aes(ymin = mean - std_err, ymax = mean + std_err),\n                width = 0.2) +\n  facet_wrap(~.metric, scales = \"free_y\") +\n  scale_fill_manual(values = c(\"#2d4563\", \"#27ae60\")) +\n  labs(title = \"Comparación de modelos\", y = \"Valor\", x = \"\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](04-laboratorio-02_files/figure-revealjs/appendix07-viz-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n- Las barras muestran la media de cada métrica; las líneas verticales son el error estándar (variabilidad entre folds)\n- Si las barras de error se superponen, la diferencia entre modelos no es robusta: probablemente no podamos decir cuál es \"mejor\" con confianza\n\n[[Volver a la comparación numérica]{.button}](#sec:evaluar-todos)\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}