{
  "hash": "c650c1070e9a235db7ddc21fc7eb1234",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tarea 1: Clasificación con tidymodels — Respuestas\"\nsubtitle: \"IA para Científicos Sociales - UCU\"\nauthor: \"Danilo Freire\"\ndate: \"2026-04-12\"\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    number-sections: true\n    code-fold: false\nlang: es\nengine: knitr\n---\n\n## Instrucciones\n\nEsta es la clave de respuestas de la Tarea 1. Cada pregunta incluye el código R completo y una respuesta escrita.\n\n### Configuración\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidymodels)\nlibrary(tidyverse)\n\ndatos <- read_csv(\"datos/desarrollo_municipios.csv\", show_col_types = FALSE)\n# Leé el archivo directo desde la web:\n# datos <- read_csv(\"https://raw.githubusercontent.com/danilofreire/introduccion-ia-ucu/main/clases/dia-01/datos/desarrollo_municipios.csv\", show_col_types = FALSE)\n\ndatos <- datos |>\n  mutate(desarrollo_alto = factor(desarrollo_alto, levels = c(\"no\", \"si\")))\n```\n:::\n\n\n## Exploración y preprocesamiento\n\n### Pregunta 1: Resumen por país\n\nCalculen la media de `ingreso_promedio` y `acceso_agua` por país. ¿Qué país tiene los municipios más ricos en promedio? ¿El ranking de agua coincide con el de ingreso?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos |>\n  group_by(pais) |>\n  summarise(\n    municipios = n(),\n    ingreso_medio = round(mean(ingreso_promedio)),\n    agua_media = round(mean(acceso_agua), 1)\n  ) |>\n  arrange(desc(ingreso_medio))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  pais      municipios ingreso_medio agua_media\n  <chr>          <int>         <dbl>      <dbl>\n1 Brasil            50           986       77.8\n2 Uruguay           58           951       80  \n3 Colombia          45           942       75.9\n4 Perú              51           925       77  \n5 Argentina         46           902       78.5\n6 México            50           864       75.9\n```\n\n\n:::\n:::\n\n\n**Respuesta:** Los municipios de **Brasil** tienen el ingreso promedio más alto (~986 USD), seguidos de cerca por Uruguay y Colombia; México queda último (~864 USD). El ranking de acceso a agua **no coincide exactamente**: Uruguay encabeza el agua (~80%) aunque es segundo en ingreso. Las diferencias entre países son chicas comparadas con la variación entre municipios dentro de cada país, lo que anticipa que `pais` no sería un gran predictor: la acción está a nivel municipal.\n\n### Pregunta 2: Visualización de distribuciones\n\nCreen un histograma de `escolaridad_media` con una línea vertical en la mediana, y otro de `poblacion`. ¿Qué diferencia notan entre las dos distribuciones?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(datos, aes(x = escolaridad_media)) +\n  geom_histogram(bins = 25, fill = \"#2d4563\", color = \"white\") +\n  geom_vline(xintercept = median(datos$escolaridad_media),\n             color = \"#c0392b\", linewidth = 1, linetype = \"dashed\") +\n  labs(title = \"Escolaridad media por municipio\",\n       x = \"Años de escolaridad\", y = \"Municipios\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](tarea-01-respuestas_files/figure-html/p2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(datos, aes(x = poblacion)) +\n  geom_histogram(bins = 25, fill = \"#2d4563\", color = \"white\") +\n  geom_vline(xintercept = median(datos$poblacion),\n             color = \"#c0392b\", linewidth = 1, linetype = \"dashed\") +\n  labs(title = \"Población por municipio\",\n       x = \"Población (miles)\", y = \"Municipios\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](tarea-01-respuestas_files/figure-html/p2-2.png){width=672}\n:::\n:::\n\n\n**Respuesta:** La escolaridad media es aproximadamente **simétrica** alrededor de su mediana (~8,6 años), con forma de campana. La población, en cambio, está **fuertemente sesgada a la derecha**: la mayoría de los municipios son chicos y unos pocos son muy grandes, así que la media queda bastante por encima de la mediana. Es el patrón típico de variables de tamaño (población, ingreso bruto), y la razón por la que muchas veces se las transforma con logaritmo antes de modelar.\n\n### Pregunta 3: Correlaciones\n\nCalculen la matriz de correlaciones entre los 8 predictores numéricos. ¿Cuáles dos variables tienen la correlación más alta (en valor absoluto)?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmat_cor <- datos |>\n  select(where(is.numeric)) |>\n  cor()\n\nround(mat_cor, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       ingreso_promedio escolaridad_media acceso_agua\ningreso_promedio                   1.00              0.63        0.57\nescolaridad_media                  0.63              1.00        0.62\nacceso_agua                        0.57              0.62        1.00\nacceso_electricidad                0.56              0.60        0.56\nempleo_formal                      0.68              0.63        0.58\ndistancia_capital                 -0.18             -0.14       -0.13\npoblacion                          0.25              0.34        0.22\npresupuesto_per_capita             0.30              0.33        0.31\n                       acceso_electricidad empleo_formal distancia_capital\ningreso_promedio                      0.56          0.68             -0.18\nescolaridad_media                     0.60          0.63             -0.14\nacceso_agua                           0.56          0.58             -0.13\nacceso_electricidad                   1.00          0.62             -0.12\nempleo_formal                         0.62          1.00             -0.16\ndistancia_capital                    -0.12         -0.16              1.00\npoblacion                             0.24          0.34             -0.13\npresupuesto_per_capita                0.29          0.35             -0.11\n                       poblacion presupuesto_per_capita\ningreso_promedio            0.25                   0.30\nescolaridad_media           0.34                   0.33\nacceso_agua                 0.22                   0.31\nacceso_electricidad         0.24                   0.29\nempleo_formal               0.34                   0.35\ndistancia_capital          -0.13                  -0.11\npoblacion                   1.00                   0.22\npresupuesto_per_capita      0.22                   1.00\n```\n\n\n:::\n\n```{.r .cell-code}\n# Buscar el par con mayor correlación absoluta\nas.data.frame(as.table(mat_cor)) |>\n  filter(as.character(Var1) < as.character(Var2)) |>\n  arrange(desc(abs(Freq))) |>\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Var1              Var2      Freq\n1     empleo_formal  ingreso_promedio 0.6799916\n2 escolaridad_media  ingreso_promedio 0.6321148\n3     empleo_formal escolaridad_media 0.6302012\n```\n\n\n:::\n:::\n\n\n**Respuesta:** El par con la correlación más alta es **`empleo_formal` e `ingreso_promedio`** (~0,68), seguido de cerca por escolaridad e ingreso (~0,63). Tiene todo el sentido teórico: donde hay más empleo formal, los hogares declaran más ingreso, y la escolaridad acompaña a ambos. Estas correlaciones moderadas-altas entre predictores anticipan el fenómeno de la Pregunta 13: cuando varios predictores comparten información, algunos van a quedar \"opacados\" en el modelo multivariado.\n\n## División y entrenamiento\n\n### Pregunta 4: División estratificada\n\nSaquen `municipio` y `pais`, dividan 80/20 con estratificación por `desarrollo_alto` y `set.seed(42)`. Verifiquen las proporciones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos_modelo <- datos |>\n  select(-municipio, -pais)\n\nset.seed(42)\nsplit <- initial_split(datos_modelo, prop = 0.80, strata = desarrollo_alto)\n\ntrain <- training(split)\ntest  <- testing(split)\n\ncat(\"Entrenamiento:\", nrow(train), \"observaciones\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEntrenamiento: 240 observaciones\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Prueba:\", nrow(test), \"observaciones\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrueba: 60 observaciones\n```\n\n\n:::\n\n```{.r .cell-code}\n# Proporciones en entrenamiento\ntrain |>\n  count(desarrollo_alto) |>\n  mutate(prop = round(n / sum(n), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  desarrollo_alto     n  prop\n  <fct>           <int> <dbl>\n1 no                128 0.533\n2 si                112 0.467\n```\n\n\n:::\n\n```{.r .cell-code}\n# Proporciones en prueba\ntest |>\n  count(desarrollo_alto) |>\n  mutate(prop = round(n / sum(n), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  desarrollo_alto     n  prop\n  <fct>           <int> <dbl>\n1 no                 32 0.533\n2 si                 28 0.467\n```\n\n\n:::\n:::\n\n\n**Respuesta:** El conjunto de entrenamiento tiene 240 observaciones y el de prueba 60. Gracias a la estratificación, las proporciones de `\"si\"` y `\"no\"` son casi idénticas en ambos conjuntos (~47% de municipios con desarrollo alto). Sin estratificar, con una muestra de prueba de solo 60 municipios, el azar podría dejar un conjunto de prueba bastante desbalanceado.\n\n### Pregunta 5: La línea base\n\nCalculen la accuracy de un \"modelo\" que siempre predice la clase mayoritaria de `desarrollo_alto` en el conjunto de prueba.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest |>\n  count(desarrollo_alto) |>\n  mutate(prop = round(n / sum(n), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  desarrollo_alto     n  prop\n  <fct>           <int> <dbl>\n1 no                 32 0.533\n2 si                 28 0.467\n```\n\n\n:::\n\n```{.r .cell-code}\nbaseline_acc <- test |>\n  count(desarrollo_alto) |>\n  mutate(prop = n / sum(n)) |>\n  summarise(baseline = max(prop)) |>\n  pull(baseline)\n\ncat(\"Accuracy de la línea base (clase mayoritaria):\", round(baseline_acc, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAccuracy de la línea base (clase mayoritaria): 0.533 \n```\n\n\n:::\n:::\n\n\n**Respuesta:** La clase mayoritaria en el conjunto de prueba es `\"no\"` con ~53%: predecir siempre `\"no\"` acierta el **53,3%** de las veces sin usar ningún predictor. Esa es la \"tasa de no-información\", el piso que cualquier modelo útil debe superar. Una accuracy del 70% suena bien en abstracto, pero solo significa algo en relación con este piso.\n\n### Pregunta 6: ¿Cuánto mejora el modelo completo?\n\nAjusten el modelo logístico completo con los 8 predictores y comparen su accuracy con la línea base.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_log <- logistic_reg() |>\n  set_engine(\"glm\") |>\n  set_mode(\"classification\")\n\najuste_completo <- modelo_log |>\n  fit(desarrollo_alto ~ ., data = train)\n\npred_completo <- ajuste_completo |>\n  predict(test) |>\n  bind_cols(test)\n\nacc_completo <- pred_completo |>\n  accuracy(truth = desarrollo_alto, estimate = .pred_class)\n\ncat(\"Línea base (clase mayoritaria):\", round(baseline_acc, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLínea base (clase mayoritaria): 0.533 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Accuracy modelo completo:\", round(acc_completo$.estimate, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAccuracy modelo completo: 0.85 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mejora sobre la línea base:\",\n    round(acc_completo$.estimate - baseline_acc, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMejora sobre la línea base: 0.317 \n```\n\n\n:::\n:::\n\n\n**Respuesta:** El modelo completo alcanza una accuracy de **0,85** en el conjunto de prueba, unos **32 puntos porcentuales** por encima de la línea base (0,53). Los predictores aportan información real sobre el nivel de desarrollo. Esta es la comparación que importa: el mismo 85% sería decepcionante si la clase mayoritaria ya representara el 84% de los casos.\n\n## Evaluación\n\n### Pregunta 7: Matriz de confusión\n\nConstruyan la matriz de confusión sobre el conjunto de prueba. ¿Cuántos falsos positivos y falsos negativos hay?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc <- conf_mat(pred_completo, truth = desarrollo_alto, estimate = .pred_class)\nmc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Truth\nPrediction no si\n        no 27  4\n        si  5 24\n```\n\n\n:::\n\n```{.r .cell-code}\nautoplot(mc, type = \"heatmap\") +\n  labs(title = \"Matriz de confusión - modelo completo\")\n```\n\n::: {.cell-output-display}\n![](tarea-01-respuestas_files/figure-html/p7-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntabla <- mc$table\nfp <- tabla[\"si\", \"no\"]  # predicho si, real no\nfn <- tabla[\"no\", \"si\"]  # predicho no, real si\ncat(\"Falsos positivos (predicho si, real no):\", fp, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFalsos positivos (predicho si, real no): 5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Falsos negativos (predicho no, real si):\", fn, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFalsos negativos (predicho no, real si): 4 \n```\n\n\n:::\n:::\n\n\n**Respuesta:** El modelo comete **5 falsos positivos** (municipios que predijo como desarrollados pero no lo son) y **4 falsos negativos** (municipios desarrollados que no identificó). Los dos tipos de error son igual de frecuentes en términos prácticos; con 60 casos de prueba, una diferencia de un error no es interpretable. Lo que importa para la decisión de política no es cuál error es más frecuente sino cuál es más costoso, y eso lo discutimos en la pregunta siguiente.\n\n### Pregunta 8: Precisión vs. recall\n\nCalculen precisión y recall (`event_level = \"second\"`). En el escenario de los subsidios (un falso positivo = cortarle los fondos a un municipio que los necesita), ¿qué métrica priorizarían?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprec <- pred_completo |>\n  precision(truth = desarrollo_alto, estimate = .pred_class,\n            event_level = \"second\")\nrec <- pred_completo |>\n  recall(truth = desarrollo_alto, estimate = .pred_class,\n         event_level = \"second\")\n\ncat(\"Precisión:\", round(prec$.estimate, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrecisión: 0.828 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Recall:\", round(rec$.estimate, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRecall: 0.857 \n```\n\n\n:::\n:::\n\n\n**Respuesta:** La precisión es **~0,83** y el recall **~0,86**. En este escenario el error caro es el falso positivo: declarar \"desarrollado\" a un municipio que no lo es significa cortarle los subsidios a una población que todavía los necesita. Por eso priorizaríamos la [precisión]{.alert}: queremos que, cuando el modelo dice \"si\", casi siempre sea verdad. Un falso negativo (mantener fondos en un municipio que ya se desarrolló) también cuesta dinero, pero su consecuencia social es mucho menos grave.\n\n### Pregunta 9: Efecto del umbral\n\nCalculen precisión y recall para los umbrales 0.2, 0.35, 0.5, 0.65 y 0.8. ¿Qué umbral elegirían para el escenario de los subsidios?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_probs <- ajuste_completo |>\n  predict(test, type = \"prob\") |>\n  bind_cols(test)\n\ntabla_umbrales <- bind_rows(\n  pred_probs |> mutate(umbral = 0.2),\n  pred_probs |> mutate(umbral = 0.35),\n  pred_probs |> mutate(umbral = 0.5),\n  pred_probs |> mutate(umbral = 0.65),\n  pred_probs |> mutate(umbral = 0.8)\n) |>\n  mutate(\n    .pred_u = if_else(.pred_si >= umbral, \"si\", \"no\"),\n    .pred_u = factor(.pred_u, levels = c(\"no\", \"si\"))\n  ) |>\n  group_by(umbral) |>\n  summarise(\n    precision = precision_vec(desarrollo_alto, .pred_u,\n                              event_level = \"second\"),\n    recall    = recall_vec(desarrollo_alto, .pred_u,\n                           event_level = \"second\")\n  )\n\ntabla_umbrales |>\n  mutate(across(c(precision, recall), \\(x) round(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  umbral precision recall\n   <dbl>     <dbl>  <dbl>\n1   0.2      0.619  0.929\n2   0.35     0.684  0.929\n3   0.5      0.828  0.857\n4   0.65     0.85   0.607\n5   0.8      0.867  0.464\n```\n\n\n:::\n:::\n\n\n**Respuesta:** La tabla muestra el intercambio clásico: con umbral 0,2 el recall es altísimo (~0,93) pero la precisión cae a ~0,62; con umbral 0,8 la precisión sube a ~0,87 pero el recall se desploma a ~0,46. Para el escenario de los subsidios conviene un umbral **alto (0,65 o incluso 0,8)**: sólo \"graduamos\" a un municipio cuando el modelo está muy seguro, minimizando los falsos positivos que son el error socialmente caro. El precio es revisar a mano (o seguir financiando) municipios desarrollados que el modelo no detectó.\n\n### Pregunta 10: Curva ROC y AUC\n\nGrafiquen la curva ROC y calculen el AUC (`event_level = \"second\"`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_probs |>\n  roc_curve(truth = desarrollo_alto, .pred_si, event_level = \"second\") |>\n  autoplot() +\n  labs(title = \"Curva ROC - modelo completo\")\n```\n\n::: {.cell-output-display}\n![](tarea-01-respuestas_files/figure-html/p10-1.png){width=672}\n:::\n\n```{.r .cell-code}\npred_probs |>\n  roc_auc(truth = desarrollo_alto, .pred_si, event_level = \"second\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.888\n```\n\n\n:::\n:::\n\n\n**Respuesta:** El AUC es **~0,89**. Según la tabla de referencia del laboratorio (0,5 = azar; 0,7-0,8 = aceptable; 0,8-0,9 = bueno; >0,9 = excelente), es un modelo **bueno**, cerca de excelente: si tomamos al azar un municipio desarrollado y uno no desarrollado, el modelo le asigna mayor probabilidad al desarrollado el 89% de las veces. La ventaja del AUC sobre la accuracy es que resume el desempeño en todos los umbrales a la vez, lo cual conecta directamente con la Pregunta 9.\n\n## Validación cruzada\n\n### Pregunta 11: Validación cruzada con 10 folds\n\nRealicen validación cruzada con 10 folds. ¿La accuracy del conjunto de prueba (Pregunta 6) cae dentro de media ± 2 errores estándar?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nfolds10 <- vfold_cv(train, v = 10, strata = desarrollo_alto)\n\nres_cv10 <- fit_resamples(modelo_log, desarrollo_alto ~ ., resamples = folds10)\ncollect_metrics(res_cv10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  .metric     .estimator  mean     n std_err .config        \n  <chr>       <chr>      <dbl> <int>   <dbl> <chr>          \n1 accuracy    binary     0.782    10  0.0363 pre0_mod0_post0\n2 brier_class binary     0.157    10  0.0189 pre0_mod0_post0\n3 roc_auc     binary     0.857    10  0.0313 pre0_mod0_post0\n```\n\n\n:::\n\n```{.r .cell-code}\nacc_cv <- collect_metrics(res_cv10) |> filter(.metric == \"accuracy\")\ncat(\"Rango (media ± 2 SE): [\",\n    round(acc_cv$mean - 2 * acc_cv$std_err, 3), \",\",\n    round(acc_cv$mean + 2 * acc_cv$std_err, 3), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRango (media ± 2 SE): [ 0.71 , 0.855 ]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Accuracy en test (Pregunta 6):\", round(acc_completo$.estimate, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAccuracy en test (Pregunta 6): 0.85 \n```\n\n\n:::\n:::\n\n\n**Respuesta:** La validación cruzada estima una accuracy promedio cercana a **0,78** con un error estándar de ~0,04, es decir un rango de aproximadamente [0,71; 0,86]. La accuracy del conjunto de prueba (0,85) queda en la parte alta de ese rango: es consistente, aunque sugiere que esta partición de prueba en particular fue algo \"fácil\". Es un buen recordatorio de que una única partición train/test da una estimación ruidosa, y la validación cruzada da una idea más honesta de la variabilidad.\n\n### Pregunta 12: Modelo reducido\n\nAjusten un modelo con los 4 predictores de menor p-valor y comparen su accuracy (CV, 5 folds) con la del modelo completo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identificar los 4 predictores con menor p-valor\ntidy(ajuste_completo) |>\n  filter(term != \"(Intercept)\") |>\n  arrange(p.value) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  term                   estimate std.error statistic p.value\n  <chr>                     <dbl>     <dbl>     <dbl>   <dbl>\n1 ingreso_promedio         0.0023    0.0007     3.55   0.0004\n2 acceso_agua              0.0612    0.019      3.22   0.0013\n3 presupuesto_per_capita   0.0038    0.0017     2.26   0.0241\n4 distancia_capital       -0.0023    0.0013    -1.76   0.0785\n5 poblacion                0.0054    0.0039     1.38   0.168 \n6 escolaridad_media        0.143     0.136      1.05   0.294 \n7 acceso_electricidad     -0.0234    0.0289    -0.810  0.418 \n8 empleo_formal            0.0133    0.0176     0.754  0.451 \n```\n\n\n:::\n\n```{.r .cell-code}\nformula_reducida <- desarrollo_alto ~ ingreso_promedio + acceso_agua +\n                      presupuesto_per_capita + distancia_capital\n\nset.seed(123)\nfolds5 <- vfold_cv(train, v = 5, strata = desarrollo_alto)\n\nres_completo <- fit_resamples(modelo_log, desarrollo_alto ~ .,\n                              resamples = folds5)\nres_reducido <- fit_resamples(modelo_log, formula_reducida,\n                              resamples = folds5)\n\nbind_rows(\n  collect_metrics(res_completo) |> mutate(modelo = \"completo (8)\"),\n  collect_metrics(res_reducido) |> mutate(modelo = \"reducido (4)\")\n) |>\n  filter(.metric == \"accuracy\") |>\n  select(modelo, mean, std_err) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  modelo        mean std_err\n  <chr>        <dbl>   <dbl>\n1 completo (8) 0.761   0.033\n2 reducido (4) 0.787   0.026\n```\n\n\n:::\n:::\n\n\n**Respuesta:** Los 4 predictores con menor p-valor son `ingreso_promedio`, `acceso_agua`, `presupuesto_per_capita` y `distancia_capital`. En validación cruzada, el modelo reducido rinde **igual o levemente mejor** que el completo (~0,79 vs ~0,76), y con menor error estándar. Vale la pena el modelo reducido: misma capacidad predictiva, la mitad de las variables, y más fácil de explicar a un tomador de decisiones. Los cuatro predictores descartados aportan poca información que los otros no tengan ya (recuerden las correlaciones de la Pregunta 3).\n\n## Reflexión\n\n### Pregunta 13: Variables sin efecto\n\n¿Por qué `acceso_electricidad` y `poblacion` correlacionan con el outcome pero no son significativas en el modelo multivariado?\n\n**Respuesta:** Porque la correlación bivariada y el efecto multivariado responden preguntas distintas. `acceso_electricidad` correlaciona con `desarrollo_alto` (~0,4) porque ambos comparten causas: los municipios con más ingreso y mejor infraestructura general también tienen más electricidad. Pero una vez que el modelo ya conoce el ingreso, el agua y el empleo formal, saber además la electricidad casi no agrega información: su coeficiente queda cerca de cero y no significativo. El modelo multivariado estima el efecto de cada variable [manteniendo las demás constantes]{.alert}, y ahí la electricidad no tiene nada propio que decir. Ejemplo de la vida real: el número de libros en el hogar correlaciona con el rendimiento escolar de los hijos, pero al controlar por educación e ingreso de los padres el \"efecto libros\" casi desaparece: los libros eran un síntoma del entorno, no la causa.\n\n### Pregunta 14: ¿Recomendarían este modelo?\n\n**Respuesta:** Recomendación: **sí, pero como filtro inicial, no como decisión automática**. A favor: el modelo supera con claridad la línea base (0,85 vs 0,53 de accuracy), tiene un AUC de ~0,89 (bueno) y la validación cruzada confirma que el desempeño no es producto de una partición afortunada (~0,79 ± 0,03). En contra: con umbral 0,5 la precisión es ~0,83, es decir que aproximadamente 1 de cada 6 municipios \"graduados\" perdería subsidios sin estar realmente desarrollado, un costo social inaceptable si la decisión es automática. El error que más preocupa es el **falso positivo** (cortar fondos a quien los necesita). Propuesta concreta: usar el modelo con umbral alto (0,65-0,8) para armar la lista de candidatos a graduación, y que un equipo humano verifique cada caso antes de cortar fondos. El modelo ahorra trabajo de revisión; no reemplaza la decisión.\n",
    "supporting": [
      "tarea-01-respuestas_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}