{
  "hash": "90d8be1858c34d432e106ad595eec2d3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tarea 3: Clasificación avanzada con tidymodels -- Respuestas\"\nsubtitle: \"IA para Científicos Sociales - UCU\"\nauthor: \"Danilo Freire\"\ndate: \"2026-04-13\"\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    number-sections: true\n    code-fold: false\nlang: es\nengine: knitr\n---\n\n## Instrucciones\n\nEsta es la clave de respuestas de la Tarea 3. Cada pregunta incluye el código R completo y una respuesta escrita.\n\n### Configuración\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidymodels)\nlibrary(tidyverse)\nlibrary(ranger)\nlibrary(vip)\nlibrary(pdp)\nlibrary(xgboost)\n\nset.seed(2026)\n\ndatos <- read_csv(\"datos/latinobarometro_sim.csv\", show_col_types = FALSE)\n\ndatos <- datos |>\n  mutate(\n    pais = factor(pais),\n    zona = factor(zona),\n    genero = factor(genero),\n    uso_internet = factor(uso_internet, levels = c(\"nunca\", \"semanal\", \"diario\")),\n    voto = factor(voto, levels = c(\"no\", \"si\"))\n  )\n\n# Las métricas del laboratorio + F1 (la pide la Pregunta 12)\n# event_level = \"second\": \"si\" es la clase positiva\nmis_metricas <- metric_set(accuracy, roc_auc, precision, recall, f_meas)\n\n# División train/test (reutilizada en varias preguntas)\ndatos_split <- initial_split(datos, prop = 0.75, strata = voto)\ndatos_train <- training(datos_split)\ndatos_test <- testing(datos_split)\n\n# Receta estándar (reutilizada en varias preguntas)\nreceta <- recipe(voto ~ edad + educacion_anios + ingreso_hogar + zona +\n                 genero + confianza_gobierno + confianza_justicia +\n                 satisfaccion_democracia + percepcion_economia +\n                 uso_internet + interes_politica,\n                 data = datos_train) |>\n  step_dummy(all_nominal_predictors()) |>\n  step_normalize(all_numeric_predictors()) |>\n  step_zv(all_predictors())\n```\n:::\n\n\n## Exploración\n\n### Pregunta 1: Participación electoral por grupos\n\nCalculen la proporción de votantes (`voto == \"si\"`) por zona (urbana/rural) y por género. Muestren los resultados en una tabla. ¿Hay diferencias entre los grupos?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Proporción de votantes por zona\ncat(\"Proporción de votantes por zona:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProporción de votantes por zona:\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos |>\n  group_by(zona) |>\n  summarise(\n    n = n(),\n    n_voto_si = sum(voto == \"si\"),\n    prop_si = round(mean(voto == \"si\"), 3)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  zona       n n_voto_si prop_si\n  <fct>  <int>     <int>   <dbl>\n1 rural    114        66   0.579\n2 urbana   386       203   0.526\n```\n\n\n:::\n\n```{.r .cell-code}\n# Proporción de votantes por género\ncat(\"\\nProporción de votantes por género:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nProporción de votantes por género:\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos |>\n  group_by(genero) |>\n  summarise(\n    n = n(),\n    n_voto_si = sum(voto == \"si\"),\n    prop_si = round(mean(voto == \"si\"), 3)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  genero     n n_voto_si prop_si\n  <fct>  <int>     <int>   <dbl>\n1 hombre   252       136   0.54 \n2 mujer    248       133   0.536\n```\n\n\n:::\n\n```{.r .cell-code}\n# Cruce zona x género\ncat(\"\\nProporción de votantes por zona y género:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nProporción de votantes por zona y género:\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos |>\n  group_by(zona, genero) |>\n  summarise(\n    n = n(),\n    prop_si = round(mean(voto == \"si\"), 3),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  zona   genero     n prop_si\n  <fct>  <fct>  <int>   <dbl>\n1 rural  hombre    66   0.561\n2 rural  mujer     48   0.604\n3 urbana hombre   186   0.532\n4 urbana mujer    200   0.52 \n```\n\n\n:::\n:::\n\n\n**Respuesta:** Las diferencias entre zona urbana y rural son pequeñas, al igual que las diferencias entre hombres y mujeres. Esto es consistente con el diseño del dataset simulado, donde zona y género tienen efectos débiles sobre la probabilidad de votar. En datos reales del Latinobarómetro, estas diferencias suelen ser más marcadas.\n\n### Pregunta 2: Correlaciones entre predictores\n\nCalculen la matriz de correlaciones entre las variables numéricas. ¿Cuáles dos variables tienen la mayor correlación? ¿Tiene sentido teórico?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvars_num <- datos |>\n  select(edad, educacion_anios, ingreso_hogar,\n         confianza_gobierno, confianza_justicia,\n         satisfaccion_democracia, percepcion_economia,\n         interes_politica, satisfaccion_vida)\n\nmat_cor <- cor(vars_num)\nround(mat_cor, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         edad educacion_anios ingreso_hogar confianza_gobierno\nedad                     1.00           -0.04         -0.06              -0.03\neducacion_anios         -0.04            1.00          0.54               0.05\ningreso_hogar           -0.06            0.54          1.00              -0.03\nconfianza_gobierno      -0.03            0.05         -0.03               1.00\nconfianza_justicia       0.05           -0.03         -0.04               0.18\nsatisfaccion_democracia  0.00           -0.01         -0.02               0.17\npercepcion_economia      0.08           -0.01         -0.08               0.02\ninteres_politica        -0.06            0.04          0.02               0.38\nsatisfaccion_vida        0.08            0.36          0.33               0.24\n                        confianza_justicia satisfaccion_democracia\nedad                                  0.05                    0.00\neducacion_anios                      -0.03                   -0.01\ningreso_hogar                        -0.04                   -0.02\nconfianza_gobierno                    0.18                    0.17\nconfianza_justicia                    1.00                    0.09\nsatisfaccion_democracia               0.09                    1.00\npercepcion_economia                  -0.04                   -0.03\ninteres_politica                      0.01                    0.16\nsatisfaccion_vida                     0.01                    0.21\n                        percepcion_economia interes_politica satisfaccion_vida\nedad                                   0.08            -0.06              0.08\neducacion_anios                       -0.01             0.04              0.36\ningreso_hogar                         -0.08             0.02              0.33\nconfianza_gobierno                     0.02             0.38              0.24\nconfianza_justicia                    -0.04             0.01              0.01\nsatisfaccion_democracia               -0.03             0.16              0.21\npercepcion_economia                    1.00            -0.02              0.14\ninteres_politica                      -0.02             1.00              0.17\nsatisfaccion_vida                      0.14             0.17              1.00\n```\n\n\n:::\n\n```{.r .cell-code}\n# Par con mayor correlación\nmat_cor_abs <- abs(mat_cor)\ndiag(mat_cor_abs) <- 0\nmax_idx <- which(mat_cor_abs == max(mat_cor_abs), arr.ind = TRUE)[1, ]\ncat(\"\\nPar con mayor correlación:\",\n    names(vars_num)[max_idx[1]], \"y\",\n    names(vars_num)[max_idx[2]], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPar con mayor correlación: ingreso_hogar y educacion_anios \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Correlación:\", round(mat_cor[max_idx[1], max_idx[2]], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCorrelación: 0.539 \n```\n\n\n:::\n:::\n\n\n**Respuesta:** Las variables con mayor correlación son `ingreso_hogar` y `educacion_anios` (r ≈ 0.54), lo cual tiene sentido: personas con más educación tienden a tener mayores ingresos. También hay correlación entre `interes_politica` y `confianza_gobierno`, ya que personas más interesadas en política pueden tener opiniones más formadas sobre el gobierno. Las correlaciones entre actitudes políticas (confianza en gobierno, en justicia, satisfacción democrática) son moderadas, reflejando que estas actitudes están relacionadas entre sí.\n\n### Pregunta 3: Distribución de edad por voto\n\nCreen un boxplot que muestre la distribución de `edad` separada por `voto`. ¿Los votantes tienden a ser mayores o menores que los no votantes?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(datos, aes(x = voto, y = edad, fill = voto)) +\n  geom_boxplot() +\n  scale_fill_manual(values = c(\"si\" = \"#27AE60\", \"no\" = \"#E74C3C\")) +\n  labs(title = \"Distribución de edad por participación electoral\",\n       x = \"¿Votó en la última elección?\",\n       y = \"Edad\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](tarea-03-respuestas_files/figure-html/p3-1.png){width=768}\n:::\n:::\n\n\n**Respuesta:** Los votantes tienden a ser mayores que los no votantes. La mediana de edad del grupo \"si\" es superior a la del grupo \"no\". Esto tiene sentido tanto teórico como empírico: la participación electoral tiende a aumentar con la edad en la mayoría de los países, ya que las personas mayores tienen mayor arraigo cívico y hábito de voto.\n\n## Modelos base\n\n### Pregunta 4: Modelo reducido\n\nDividan los datos y ajusten una regresión logística con solo tres predictores. ¿Cómo se compara con el modelo completo?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Receta reducida (solo 3 predictores)\nreceta_reducida <- recipe(voto ~ edad + educacion_anios + interes_politica,\n                          data = datos_train) |>\n  step_normalize(all_numeric_predictors())\n\nmodelo_logit <- logistic_reg() |>\n  set_engine(\"glm\") |>\n  set_mode(\"classification\")\n\n# Modelo reducido\najuste_reducido <- workflow() |>\n  add_recipe(receta_reducida) |>\n  add_model(modelo_logit) |>\n  fit(data = datos_train)\n\npred_reducido <- augment(ajuste_reducido, datos_test)\n\nmetricas_reducido <- pred_reducido |>\n  mis_metricas(truth = voto, estimate = .pred_class, .pred_si,\n               event_level = \"second\")\n\ncat(\"Modelo reducido (3 predictores):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModelo reducido (3 predictores):\n```\n\n\n:::\n\n```{.r .cell-code}\nmetricas_reducido\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  .metric   .estimator .estimate\n  <chr>     <chr>          <dbl>\n1 accuracy  binary         0.635\n2 precision binary         0.645\n3 recall    binary         0.721\n4 f_meas    binary         0.681\n5 roc_auc   binary         0.637\n```\n\n\n:::\n\n```{.r .cell-code}\n# Modelo completo para comparar\najuste_completo <- workflow() |>\n  add_recipe(receta) |>\n  add_model(modelo_logit) |>\n  fit(data = datos_train)\n\npred_completo <- augment(ajuste_completo, datos_test)\n\nmetricas_completo <- pred_completo |>\n  mis_metricas(truth = voto, estimate = .pred_class, .pred_si,\n               event_level = \"second\")\n\ncat(\"\\nModelo completo (11 predictores):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModelo completo (11 predictores):\n```\n\n\n:::\n\n```{.r .cell-code}\nmetricas_completo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  .metric   .estimator .estimate\n  <chr>     <chr>          <dbl>\n1 accuracy  binary         0.611\n2 precision binary         0.634\n3 recall    binary         0.662\n4 f_meas    binary         0.647\n5 roc_auc   binary         0.626\n```\n\n\n:::\n:::\n\n\n**Respuesta:** En esta muestra el modelo reducido con tres predictores (edad, educación e interés político) rinde apenas *mejor* que el completo en el conjunto de prueba: AUC ≈ 0.64 y accuracy ≈ 0.64, frente a AUC ≈ 0.63 y accuracy ≈ 0.61 del modelo con once predictores. No es un error: esos tres predictores son justamente los más fuertes (lo confirmamos en la pregunta 5), y agregar ocho variables débiles aporta poca señal pero sí ruido de estimación, lo que puede empeorar ligeramente el desempeño fuera de muestra. Es un recordatorio de que más predictores no implican mejor predicción: la parsimonia suele pagar, sobre todo con muestras moderadas.\n\n### Pregunta 5: Coeficientes e interpretación\n\nUsando el modelo reducido de la pregunta 4, extraigan los coeficientes con `tidy()` y calculen los odds ratios. ¿Cuál de los tres predictores tiene el efecto más fuerte? ¿Los signos van en la dirección esperada?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoefs <- tidy(ajuste_reducido) |>\n  mutate(odds_ratio = exp(estimate)) |>\n  arrange(desc(abs(statistic)))\n\ncoefs |>\n  select(term, estimate, std.error, statistic, p.value, odds_ratio)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  term             estimate std.error statistic  p.value odds_ratio\n  <chr>               <dbl>     <dbl>     <dbl>    <dbl>      <dbl>\n1 educacion_anios     0.389     0.112      3.49 0.000482       1.48\n2 interes_politica    0.333     0.111      3.00 0.00269        1.39\n3 edad                0.291     0.110      2.66 0.00792        1.34\n4 (Intercept)         0.163     0.108      1.51 0.130          1.18\n```\n\n\n:::\n:::\n\n\n**Respuesta:** Con los niveles `c(\"no\", \"si\")`, `glm()` modela la probabilidad del *segundo* nivel, P(votar), así que los coeficientes se leen de forma directa: un coeficiente positivo (odds ratio mayor que 1) aumenta la probabilidad de votar.\n\nLos coeficientes están en escala normalizada (aplicamos `step_normalize()` en la receta), así que cada uno mide el efecto de una desviación estándar del predictor y son directamente comparables. El efecto más fuerte es el de `educacion_anios` (z ≈ 3.5; odds ratio ≈ 1.48: una desviación estándar más de educación aumenta los odds de votar en ~48%), seguido por `interes_politica` (z ≈ 3.0; OR ≈ 1.39) y `edad` (z ≈ 2.7; OR ≈ 1.34). Los tres coeficientes son positivos, es decir, los tres *aumentan* la probabilidad de votar: exactamente la dirección que predice la literatura clásica de participación electoral (más recursos cognitivos, más motivación y más arraigo, más voto). Ojo: si el factor se hubiera definido al revés (`c(\"si\", \"no\")`), `glm()` modelaría P(no votar) y todos los signos aparecerían invertidos; por eso siempre conviene verificar los niveles antes de interpretar.\n\n## Random Forest y tuning\n\n### Pregunta 6: Efecto del número de árboles\n\nEntrenen RF con 100, 500 y 1000 árboles. ¿Cuánto mejora el AUC?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresultados_arboles <- data.frame(trees = numeric(), auc = numeric())\n\nfor (n_trees in c(100, 500, 1000)) {\n  modelo_temp <- rand_forest(trees = n_trees, mtry = 4, min_n = 10) |>\n    set_engine(\"ranger\") |>\n    set_mode(\"classification\")\n\n  ajuste_temp <- workflow() |>\n    add_recipe(receta) |>\n    add_model(modelo_temp) |>\n    fit(data = datos_train)\n\n  auc_val <- ajuste_temp |>\n    augment(datos_test) |>\n    roc_auc(truth = voto, .pred_si, event_level = \"second\") |>\n    pull(.estimate)\n\n  resultados_arboles <- rbind(resultados_arboles,\n                              data.frame(trees = n_trees, auc = round(auc_val, 4)))\n}\n\nresultados_arboles\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  trees    auc\n1   100 0.5477\n2   500 0.5718\n3  1000 0.5682\n```\n\n\n:::\n:::\n\n\n**Respuesta:** La diferencia entre 100 y 500 árboles suele ser pequeña (1-2 puntos de AUC), y entre 500 y 1000 es aún menor. En general, 500 árboles es suficiente para la mayoría de los problemas. El rendimiento de Random Forest se estabiliza rápidamente con más árboles, pero el tiempo de cómputo sigue creciendo de forma lineal. Para datasets pequeños como este (500 observaciones), 500 árboles es un buen punto de equilibrio.\n\n### Pregunta 7: Grilla aleatoria vs. regular\n\nUsen `grid_random()` con `size = 20` y comparen con `grid_regular()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_rf_tune <- rand_forest(\n  mtry = tune(),\n  trees = 500,\n  min_n = tune()\n) |>\n  set_engine(\"ranger\") |>\n  set_mode(\"classification\")\n\nwf_rf_tune <- workflow() |>\n  add_recipe(receta) |>\n  add_model(modelo_rf_tune)\n\nfolds <- vfold_cv(datos_train, v = 5, strata = voto)\n\n# Grilla regular (4x4 = 16 combinaciones)\ngrilla_reg <- grid_regular(\n  mtry(range = c(2, 8)),\n  min_n(range = c(5, 30)),\n  levels = c(4, 4)\n)\n\nres_regular <- tune_grid(\n  wf_rf_tune, resamples = folds, grid = grilla_reg,\n  metrics = metric_set(roc_auc),\n  control = control_grid(verbose = FALSE)\n)\n\nmejor_regular <- show_best(res_regular, metric = \"roc_auc\", n = 1)\ncat(\"Mejor AUC con grilla regular:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMejor AUC con grilla regular:\n```\n\n\n:::\n\n```{.r .cell-code}\nmejor_regular |> select(mtry, min_n, mean, std_err)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n   mtry min_n  mean std_err\n  <int> <int> <dbl>   <dbl>\n1     2    21 0.624  0.0252\n```\n\n\n:::\n\n```{.r .cell-code}\n# Grilla aleatoria (20 combinaciones)\nset.seed(2026)\ngrilla_rand <- grid_random(\n  mtry(range = c(2, 8)),\n  min_n(range = c(5, 30)),\n  size = 20\n)\n\nres_random <- tune_grid(\n  wf_rf_tune, resamples = folds, grid = grilla_rand,\n  metrics = metric_set(roc_auc),\n  control = control_grid(verbose = FALSE)\n)\n\nmejor_random <- show_best(res_random, metric = \"roc_auc\", n = 1)\ncat(\"\\nMejor AUC con grilla aleatoria:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMejor AUC con grilla aleatoria:\n```\n\n\n:::\n\n```{.r .cell-code}\nmejor_random |> select(mtry, min_n, mean, std_err)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n   mtry min_n  mean std_err\n  <int> <int> <dbl>   <dbl>\n1     2    17 0.615  0.0200\n```\n\n\n:::\n:::\n\n\n**Respuesta:** Ambas grillas dan resultados similares. La grilla regular explora el espacio de forma uniforme, lo cual es bueno cuando hay pocos hiperparámetros (2 en este caso). La grilla aleatoria explora combinaciones que la regular podría no probar, lo que es más eficiente cuando hay 3 o más hiperparámetros. Para este caso con solo 2 hiperparámetros, la diferencia es mínima.\n\n### Pregunta 8: ¿La validación cruzada predice el desempeño real?\n\nFinalicen el workflow con la mejor combinación de la grilla regular, ajusten sobre entrenamiento y comparen el AUC de prueba con la estimación de la validación cruzada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mejor combinación según la CV de la pregunta 7 (grilla regular)\nmejor_regular |> select(mtry, min_n, mean, std_err)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n   mtry min_n  mean std_err\n  <int> <int> <dbl>   <dbl>\n1     2    21 0.624  0.0252\n```\n\n\n:::\n\n```{.r .cell-code}\n# Finalizar, ajustar sobre TODO el entrenamiento y evaluar en prueba\najuste_rf_final <- finalize_workflow(wf_rf_tune,\n                                     mejor_regular |> select(mtry, min_n)) |>\n  fit(data = datos_train)\n\npred_rf_final <- augment(ajuste_rf_final, datos_test)\n\nauc_test <- pred_rf_final |>\n  roc_auc(truth = voto, .pred_si, event_level = \"second\")\n\ncat(\"AUC estimado por CV:\", round(mejor_regular$mean, 3),\n    \"± 2 SE = [\", round(mejor_regular$mean - 2 * mejor_regular$std_err, 3),\n    \",\", round(mejor_regular$mean + 2 * mejor_regular$std_err, 3), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAUC estimado por CV: 0.624 ± 2 SE = [ 0.574 , 0.674 ]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"AUC en el conjunto de prueba:\", round(auc_test$.estimate, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAUC en el conjunto de prueba: 0.589 \n```\n\n\n:::\n:::\n\n\n**Respuesta:** En nuestra corrida la validación cruzada estima un AUC de ~0,62 y el conjunto de prueba da ~0,59: la CV fue **levemente optimista**, pero el valor de prueba cae dentro del rango de ± 2 errores estándar, así que la estimación es honesta dentro de su incertidumbre. Ese pequeño optimismo es esperable: elegimos justamente la combinación de hiperparámetros que mejor rindió en la CV, y \"el ganador del torneo\" siempre tiene algo de suerte incluida. Por eso es tan importante que el conjunto de prueba no participe del tuning: es el único dato que el proceso de selección nunca vio, y por lo tanto la única medida no contaminada del desempeño real. Si tuneáramos contra la prueba, el AUC reportado sería sistemáticamente inflado y no sabríamos cuánto.\n\n## Interpretación\n\n### Pregunta 9: PDPs adicionales\n\nCreen PDPs para `confianza_gobierno` y `educacion_anios`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Random Forest principal con importancia (lo reusamos en VIP y comparación)\nmodelo_rf_final <- rand_forest(trees = 500, mtry = 4, min_n = 10) |>\n  set_engine(\"ranger\", importance = \"impurity\") |>\n  set_mode(\"classification\")\n\najuste_rf <- workflow() |>\n  add_recipe(receta) |>\n  add_model(modelo_rf_final) |>\n  fit(data = datos_train)\n\nrf_engine <- extract_fit_engine(ajuste_rf)\ndatos_prep <- bake(prep(receta), new_data = datos_train)\n\n# PDP para confianza_gobierno\npdp_gobierno <- partial(\n  rf_engine,\n  pred.var = \"confianza_gobierno\",\n  train = datos_prep,\n  prob = TRUE,\n  which.class = \"si\"\n)\n\np1 <- autoplot(pdp_gobierno) +\n  labs(title = \"PDP: Confianza en el gobierno\",\n       x = \"Confianza en el gobierno (normalizada)\",\n       y = \"P(voto = sí)\") +\n  theme_minimal()\n\n# PDP para educacion_anios\npdp_educacion <- partial(\n  rf_engine,\n  pred.var = \"educacion_anios\",\n  train = datos_prep,\n  prob = TRUE,\n  which.class = \"si\"\n)\n\np2 <- autoplot(pdp_educacion) +\n  labs(title = \"PDP: Años de educación\",\n       x = \"Educación (normalizada)\",\n       y = \"P(voto = sí)\") +\n  theme_minimal()\n\n# Mostrar ambos gráficos\nlibrary(patchwork)\np1 + p2\n```\n\n::: {.cell-output-display}\n![](tarea-03-respuestas_files/figure-html/p9-1.png){width=960}\n:::\n:::\n\n\n**Respuesta:** El PDP de confianza en el gobierno muestra una relación positiva: a mayor confianza, mayor probabilidad de votar. La relación puede tener una forma de escalón o ser aproximadamente lineal. El PDP de educación también muestra una relación positiva, lo cual tiene sentido: personas más educadas tienden a participar más en elecciones. Si alguna relación muestra curvas o mesetas, esto indica que Random Forest está capturando no-linealidades que la regresión logística no puede modelar.\n\n### Pregunta 10: VIP vs. coeficientes logísticos\n\nComparen el ranking del VIP con el ranking de los coeficientes logísticos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# VIP del Random Forest (Gini)\ncat(\"Ranking VIP (Random Forest, Gini):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRanking VIP (Random Forest, Gini):\n```\n\n\n:::\n\n```{.r .cell-code}\nrf_parsnip <- extract_fit_parsnip(ajuste_rf)\nimportancia_rf <- vip::vi(rf_parsnip)\nimportancia_rf |> arrange(desc(Importance))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n   Variable                Importance\n   <chr>                        <dbl>\n 1 edad                         26.3 \n 2 educacion_anios              23.2 \n 3 ingreso_hogar                15.3 \n 4 interes_politica             10.8 \n 5 confianza_justicia            9.77\n 6 percepcion_economia           9.23\n 7 confianza_gobierno            9.15\n 8 satisfaccion_democracia       7.70\n 9 genero_mujer                  3.59\n10 uso_internet_diario           3.58\n11 uso_internet_semanal          3.54\n12 zona_urbana                   3.38\n```\n\n\n:::\n\n```{.r .cell-code}\n# Ranking de coeficientes logísticos (por |z|)\ncat(\"\\nRanking de coeficientes (regresión logística, |z|):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRanking de coeficientes (regresión logística, |z|):\n```\n\n\n:::\n\n```{.r .cell-code}\ncoefs_logit <- tidy(ajuste_completo) |>\n  filter(term != \"(Intercept)\") |>\n  mutate(abs_z = abs(statistic)) |>\n  arrange(desc(abs_z)) |>\n  select(term, estimate, statistic, abs_z)\n\ncoefs_logit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 4\n   term                    estimate statistic  abs_z\n   <chr>                      <dbl>     <dbl>  <dbl>\n 1 educacion_anios          0.433      3.25   3.25  \n 2 interes_politica         0.335      2.75   2.75  \n 3 edad                     0.302      2.69   2.69  \n 4 confianza_justicia       0.247      2.16   2.16  \n 5 uso_internet_semanal     0.343      2.12   2.12  \n 6 uso_internet_diario      0.310      1.93   1.93  \n 7 zona_urbana             -0.117     -1.04   1.04  \n 8 satisfaccion_democracia  0.0943     0.829  0.829 \n 9 percepcion_economia     -0.0645    -0.576  0.576 \n10 confianza_gobierno       0.0457     0.377  0.377 \n11 ingreso_hogar           -0.0319    -0.246  0.246 \n12 genero_mujer            -0.00273   -0.0246 0.0246\n```\n\n\n:::\n:::\n\n\n**Respuesta:** Los dos rankings coinciden en la cima en `educacion_anios` y `edad`, pero divergen en puntos reveladores. El caso más claro es `ingreso_hogar`: aparece tercero en el VIP (importancia Gini) y casi último en el ranking logístico (|z| ≈ 0.25). Esto ilustra un sesgo conocido de la importancia por impureza (Gini): tiende a inflar la importancia de variables continuas con muchos valores distintos, como el ingreso, porque ofrecen más puntos de corte posibles, aunque su efecto lineal sea débil. A la inversa, `interes_politica` tiene un efecto lineal fuerte (segundo por |z|) pero queda más abajo en el VIP. Las diferencias surgen porque: (1) la importancia Gini mide cuánto reduce cada variable la impureza en los árboles, mientras que el estadístico z mide la significancia del efecto lineal; (2) Random Forest reparte la importancia entre variables correlacionadas; (3) cada método responde a una estructura distinta. Una nota: en el laboratorio usamos importancia por permutación, menos sensible a este sesgo; aquí usamos Gini a propósito para mostrar que la métrica de importancia elegida cambia el ranking.\n\n## Comparación de modelos\n\n### Pregunta 11: Agregar un árbol de decisión\n\nEntrenen un `decision_tree()` y compárenlo con los otros modelos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Árbol de decisión\nmodelo_arbol <- decision_tree(\n  cost_complexity = 0.01,\n  tree_depth = 10,\n  min_n = 10\n) |>\n  set_engine(\"rpart\") |>\n  set_mode(\"classification\")\n\najuste_arbol <- workflow() |>\n  add_recipe(receta) |>\n  add_model(modelo_arbol) |>\n  fit(data = datos_train)\n\npred_arbol <- augment(ajuste_arbol, datos_test)\n\nmetricas_arbol <- pred_arbol |>\n  mis_metricas(truth = voto, estimate = .pred_class, .pred_si,\n               event_level = \"second\")\n\ncat(\"Árbol de decisión:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nÁrbol de decisión:\n```\n\n\n:::\n\n```{.r .cell-code}\nmetricas_arbol\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  .metric   .estimator .estimate\n  <chr>     <chr>          <dbl>\n1 accuracy  binary         0.571\n2 precision binary         0.597\n3 recall    binary         0.632\n4 f_meas    binary         0.614\n5 roc_auc   binary         0.604\n```\n\n\n:::\n\n```{.r .cell-code}\n# Random Forest: reusamos ajuste_rf de la pregunta 9\npred_rf <- augment(ajuste_rf, datos_test)\nmetricas_rf <- pred_rf |>\n  mis_metricas(truth = voto, estimate = .pred_class, .pred_si,\n               event_level = \"second\")\n\ncat(\"\\nRandom Forest:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRandom Forest:\n```\n\n\n:::\n\n```{.r .cell-code}\nmetricas_rf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  .metric   .estimator .estimate\n  <chr>     <chr>          <dbl>\n1 accuracy  binary         0.548\n2 precision binary         0.575\n3 recall    binary         0.618\n4 f_meas    binary         0.596\n5 roc_auc   binary         0.570\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nRegresión logística:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRegresión logística:\n```\n\n\n:::\n\n```{.r .cell-code}\nmetricas_completo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  .metric   .estimator .estimate\n  <chr>     <chr>          <dbl>\n1 accuracy  binary         0.611\n2 precision binary         0.634\n3 recall    binary         0.662\n4 f_meas    binary         0.647\n5 roc_auc   binary         0.626\n```\n\n\n:::\n:::\n\n\n**Respuesta:** El resultado va contra la intuición habitual: en esta muestra el árbol de decisión (AUC ≈ 0.60) rinde *mejor* que el Random Forest sin tunear (AUC ≈ 0.57), y la regresión logística los supera a ambos (AUC ≈ 0.63). La regla de que \"un solo árbol es más débil que un ensemble de 500\" no se cumple aquí porque el problema es lineal, ruidoso y con pocas observaciones: el ensemble no encuentra estructura no lineal que aprovechar y la logística, bien especificada, gana. La ventaja del árbol sigue siendo su interpretabilidad: se visualiza como un diagrama de flujo que muestra exactamente cómo se decide. La lección es que un modelo más complejo no garantiza mejor desempeño; conviene compararlo siempre con un baseline lineal.\n\n### Pregunta 12: Tabla comparativa completa\n\nCreen una tabla que compare los cuatro modelos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# XGBoost (del laboratorio)\nmodelo_xgb <- boost_tree(\n  trees = 500, tree_depth = 4, learn_rate = 0.01, min_n = 10\n) |>\n  set_engine(\"xgboost\") |>\n  set_mode(\"classification\")\n\najuste_xgb <- workflow() |>\n  add_recipe(receta) |>\n  add_model(modelo_xgb) |>\n  fit(data = datos_train)\n\npred_xgb <- augment(ajuste_xgb, datos_test)\n\n# Calcular las cinco métricas para cada modelo con mis_metricas\ntabla <- bind_rows(\n  pred_completo |> mis_metricas(truth = voto, estimate = .pred_class, .pred_si,\n                                event_level = \"second\") |>\n    mutate(modelo = \"Reg. logística\"),\n  pred_rf |> mis_metricas(truth = voto, estimate = .pred_class, .pred_si,\n                          event_level = \"second\") |>\n    mutate(modelo = \"Random Forest\"),\n  pred_xgb |> mis_metricas(truth = voto, estimate = .pred_class, .pred_si,\n                           event_level = \"second\") |>\n    mutate(modelo = \"XGBoost\"),\n  pred_arbol |> mis_metricas(truth = voto, estimate = .pred_class, .pred_si,\n                             event_level = \"second\") |>\n    mutate(modelo = \"Árbol decisión\")\n)\n\n# Tabla resumen\ntabla |>\n  select(modelo, .metric, .estimate) |>\n  pivot_wider(names_from = .metric, values_from = .estimate) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 3))) |>\n  arrange(desc(roc_auc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  modelo         accuracy precision recall f_meas roc_auc\n  <chr>             <dbl>     <dbl>  <dbl>  <dbl>   <dbl>\n1 Reg. logística    0.611     0.634  0.662  0.647   0.626\n2 XGBoost           0.587     0.618  0.618  0.618   0.61 \n3 Árbol decisión    0.571     0.597  0.632  0.614   0.604\n4 Random Forest     0.548     0.575  0.618  0.596   0.57 \n```\n\n\n:::\n:::\n\n\n**Respuesta:** Ordenada por AUC, la tabla sorprende: la regresión logística queda primera (AUC ≈ 0.63), seguida de XGBoost (≈ 0.61) y el árbol (≈ 0.60), y el Random Forest sin tunear queda último (≈ 0.57). La explicación es clara: el proceso que genera el voto es esencialmente lineal en los predictores (lo diseñamos así), de modo que la regresión logística está bien especificada y es difícil de superar. Los modelos de árboles no tienen no-linealidades que explotar, y el Random Forest con hiperparámetros fijos (`mtry = 4`, `min_n = 10`) ni siquiera está tuneado: cuando lo ajustamos por validación cruzada en las preguntas 7 y 8, su AUC sube a ≈ 0.62 y prácticamente empata con la logística. La moraleja es doble: el modelo más sofisticado no siempre gana, y conviene ajustar los hiperparámetros y elegir la familia de modelos según la estructura de los datos. Las diferencias en accuracy, precisión y recall son pequeñas y refuerzan la misma conclusión.\n\n## Reflexión\n\n### Pregunta 13: Recomendación para un tomador de decisiones\n\n¿Qué modelo recomendarían para un organismo electoral? Consideren rendimiento, interpretabilidad y utilidad.\n\n**Respuesta:** Para un organismo electoral que busca entender qué factores influyen en la participación, recomendaría una **combinación de regresión logística y Random Forest**:\n\n1. **Regresión logística** como modelo principal de comunicación: sus coeficientes (odds ratios) permiten decir cosas concretas como \"por cada año adicional de edad, las chances de votar aumentan X%\". Esto es directamente útil para diseñar campañas de movilización dirigidas a grupos específicos.\n\n2. **Random Forest con VIP y PDP** como herramienta de exploración: el VIP confirma qué variables son más predictivas (sin asumir linealidad), y los PDPs revelan relaciones no lineales que la regresión logística no captura (por ejemplo, si el efecto de la edad se estabiliza a partir de cierta edad).\n\n3. **No recomendaría XGBoost** para este caso. En esta muestra su AUC es incluso menor que el de la regresión logística, así que perderíamos toda la interpretabilidad sin ganar precisión. Un funcionario público necesita poder explicar y justificar las decisiones, algo difícil con un modelo de caja negra.\n\nEn ciencias sociales aplicadas, la interpretabilidad suele ser tan importante como el rendimiento predictivo. En este caso ni siquiera hay que elegir: la regresión logística fue a la vez el modelo más interpretable y el de mejor AUC, así que la decisión es fácil. Y aun cuando exista un pequeño costo en precisión, un modelo que permite explicar y justificar las decisiones suele ser más útil para un organismo público que uno opaco con una ventaja marginal.\n",
    "supporting": [
      "tarea-03-respuestas_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}