{
  "hash": "88d4b16196700fee535b4f1fe0ab6402",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"IA para Científicos Sociales\"\nsubtitle: \"Sesión 2.4: Laboratorio 4 - Regresión y regularización\"\nauthor:\n  - name: Danilo Freire\n    orcid: 0000-0002-4712-6810\n    email: danilofreire@gmail.com\n    affiliations: \"Department of Data and Decision Sciences <br> Emory University\"\nformat:\n  clean-revealjs:\n    self-contained: true\n    footer: \"[Sesión 2.4](https://danilofreire.github.io/introduccion-ia-ucu/clases/dia-02/08-laboratorio-04.html)\"\n    transition: slide\n    transition-speed: default\n    scrollable: true\nexecute:\n  echo: true\nrevealjs-plugins:\n  - multimodal\nengine: knitr\neditor:\n  render-on-save: true\nlang: es\n---\n\n\n\n# Laboratorio 4: Regresión y regularización {background-color=\"#2d4563\"}\n\n## Objetivos del laboratorio\n\n:::{style=\"margin-top: 30px; font-size: 23px;\"}\n:::{.columns}\n:::{.column width=50%}\n**Retomamos la clase de regresión.** Hoy ejecutamos paso a paso la misma receta que vimos en la teoría:\n\n1. Preparar los datos con una `receta`\n2. Ajustar un baseline [OLS]{.alert}\n3. Tunear [LASSO]{.alert} con validación cruzada\n4. Implementar [Ridge]{.alert} por analogía (**Ejercicio 1**)\n5. Comparar los tres modelos\n6. Decidir: ¿predicción o explicación? (**Ejercicio 2**)\n:::\n\n:::{.column width=50%}\n**Lo que vamos a aprender:**\n\n- Cuándo y cómo usar [regularización]{.alert}\n- Diferencias prácticas entre [LASSO]{.alert} y [Ridge]{.alert}\n- Tuning de `penalty` con validación cruzada\n- Trade-off entre interpretabilidad y rendimiento\n\n<br>\n\n[La mayoría de los slides son demostraciones: corremos el código juntos. Solo hay 2 ejercicios, ambos con solución en el apéndice]{.alert} 🤓\n:::\n:::\n:::\n\n# Parte 1: Preparación {background-color=\"#2d4563\"}\n\n## Cargar paquetes y datos\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Si algún paquete falta: install.packages(c( \"tidymodels\", \"glmnet\", \"ranger\", \"vip\"))\nlibrary(tidymodels)  # rsample, parsnip, recipes, workflows, tune, yardstick\nlibrary(tidyverse)   # incluye readr (read_csv), dplyr, ggplot2, etc.\nlibrary(glmnet)      # motor para LASSO, Ridge, Elastic Net\n\nset.seed(2026)\n\n# Cargar el dataset\ndatos <- read_csv(\"datos/latinobarometro_sim.csv\", show_col_types = FALSE)\n# Leé el archivo directo desde la web:\n# datos <- read_csv(\"https://raw.githubusercontent.com/danilofreire/introduccion-ia-ucu/main/clases/dia-02/datos/latinobarometro_sim.csv\", show_col_types = FALSE)\n\n# Convertir categóricas a factor\ndatos <- datos |>\n  mutate(\n    pais         = factor(pais),\n    zona         = factor(zona),\n    genero       = factor(genero),\n    uso_internet = factor(uso_internet, levels = c(\"nunca\", \"semanal\", \"diario\"))\n  )\n\nglimpse(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 500\nColumns: 14\n$ pais                    <fct> Argentina, Costa Rica, Panamá, Perú, Nicaragua…\n$ edad                    <dbl> 65, 19, 82, 54, 32, 21, 57, 21, 57, 80, 38, 69…\n$ educacion_anios         <dbl> 15, 18, 11, 9, 14, 9, 7, 17, 3, 12, 12, 14, 9,…\n$ ingreso_hogar           <dbl> 7, 10, 3, 8, 5, 5, 5, 9, 3, 7, 6, 6, 5, 8, 9, …\n$ zona                    <fct> urbana, rural, urbana, urbana, urbana, urbana,…\n$ genero                  <fct> hombre, hombre, mujer, mujer, hombre, hombre, …\n$ confianza_gobierno      <dbl> 2, 3, 2, 4, 5, 5, 2, 4, 3, 1, 1, 2, 3, 3, 3, 3…\n$ confianza_justicia      <dbl> 3, 3, 3, 2, 4, 2, 2, 4, 2, 3, 3, 2, 4, 3, 4, 3…\n$ satisfaccion_democracia <dbl> 2, 1, 2, 2, 4, 3, 3, 4, 3, 3, 2, 4, 2, 2, 2, 3…\n$ percepcion_economia     <dbl> 3, 5, 5, 5, 2, 5, 4, 2, 3, 3, 4, 4, 4, 1, 2, 4…\n$ uso_internet            <fct> semanal, diario, diario, diario, nunca, semana…\n$ interes_politica        <dbl> 3, 3, 3, 3, 3, 4, 4, 1, 1, 1, 1, 1, 2, 1, 3, 1…\n$ satisfaccion_vida       <dbl> 8.6, 8.3, 5.3, 7.8, 6.3, 8.7, 5.9, 6.4, 4.5, 6…\n$ voto                    <chr> \"no\", \"si\", \"si\", \"no\", \"si\", \"si\", \"no\", \"si\"…\n```\n\n\n:::\n:::\n\n:::\n\n## Dividir los datos\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# División train/test (75/25)\ndatos_split <- initial_split(datos, prop = 0.75)\ndatos_train <- training(datos_split)\ndatos_test  <- testing(datos_split)\n\ncat(\"Train:\", nrow(datos_train), \"obs | Test:\", nrow(datos_test), \"obs\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrain: 375 obs | Test: 125 obs\n```\n\n\n:::\n:::\n\n\n- La variable objetivo es `satisfaccion_vida` (1-10, continua)\n- Train tendrá ~375 obs, test ~125\n:::\n\n## Receta de preprocesamiento\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Predecir con todas las variables menos voto (outcome del Lab 3) y pais (alta cardinalidad)\nreceta <- recipe(satisfaccion_vida ~ ., data = datos_train) |>\n  step_rm(pais, voto) |>                       # eliminar variables no predictivas o con demasiados niveles\n  step_dummy(all_nominal_predictors()) |>      # categóricas → dummies\n  step_normalize(all_numeric_predictors()) |>  # normalizar (importante para regularización)\n  step_zv(all_predictors())                    # eliminar varianza cero\n\n# Verificar\n# prep() = preparar la receta con los datos de train; juice() = extraer el dataset preprocesado\nreceta |> prep() |> juice() |> glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 375\nColumns: 13\n$ edad                    <dbl> 1.2595504, -0.4806457, -0.3751792, 1.1013507, …\n$ educacion_anios         <dbl> 0.71927007, -0.76410084, -0.02241538, -0.26964…\n$ ingreso_hogar           <dbl> -0.6428788, -1.0960358, -0.1897217, 0.7165923,…\n$ confianza_gobierno      <dbl> -0.3060254, 0.7974315, -1.4094822, -0.3060254,…\n$ confianza_justicia      <dbl> -0.5648555, 0.4535138, -1.5832247, -0.5648555,…\n$ satisfaccion_democracia <dbl> 0.5461895, -0.5491103, -0.5491103, 0.5461895, …\n$ percepcion_economia     <dbl> 1.57455077, -0.08170881, -0.90983860, 0.746420…\n$ interes_politica        <dbl> 1.5995530, 1.5995530, -0.4546675, -0.4546675, …\n$ satisfaccion_vida       <dbl> 7.6, 6.3, 7.2, 6.0, 6.3, 5.5, 7.4, 8.5, 4.3, 3…\n$ zona_urbana             <dbl> -1.8877612, 0.5283154, 0.5283154, 0.5283154, 0…\n$ genero_mujer            <dbl> -1.0450130, 0.9543741, -1.0450130, -1.0450130,…\n$ uso_internet_semanal    <dbl> -0.598113, -0.598113, -0.598113, 1.667466, -0.…\n$ uso_internet_diario     <dbl> 0.8154072, -1.2231108, 0.8154072, -1.2231108, …\n```\n\n\n:::\n:::\n\n:::\n\n# Parte 2: OLS baseline {background-color=\"#2d4563\"}\n\n## OLS: spec y ajuste\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Regresión lineal con motor lm\nmodelo_ols <- linear_reg() |>\n  set_engine(\"lm\") |>\n  set_mode(\"regression\")\n\n# Workflow + ajuste (combinados en una pipeline)\najuste_ols <- workflow() |>\n  add_recipe(receta) |>\n  add_model(modelo_ols) |>\n  fit(data = datos_train)\n\n# Coeficientes ordenados por magnitud (top 5)\ntidy(ajuste_ols) |>\n  arrange(desc(abs(estimate))) |>\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term                    estimate std.error statistic   p.value\n  <chr>                      <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)                6.72     0.0628    107.   4.01e-276\n2 educacion_anios            0.382    0.0734      5.21 3.23e-  7\n3 satisfaccion_democracia    0.261    0.0652      4.01 7.51e-  5\n4 confianza_gobierno         0.250    0.0717      3.48 5.62e-  4\n5 ingreso_hogar              0.223    0.0734      3.05 2.49e-  3\n```\n\n\n:::\n:::\n\n\n- `ajuste_ols` ya tiene el modelo ajustado a `datos_train`\n- En el próximo slide lo evaluamos en test\n:::\n\n## Evaluar OLS en test\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Generar predicciones (augment() añade .pred al test set)\npred_ols <- augment(ajuste_ols, datos_test)\n\n# Calcular métricas en test\nmetricas_ols <- pred_ols |>\n  metrics(truth = satisfaccion_vida, estimate = .pred)\n\nmetricas_ols |> knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|.metric |.estimator | .estimate|\n|:-------|:----------|---------:|\n|rmse    |standard   |     1.190|\n|rsq     |standard   |     0.264|\n|mae     |standard   |     0.945|\n\n\n:::\n:::\n\n\n:::{style=\"margin-top:30px;\"}\n- RMSE ≈ 1.2: en promedio la predicción se aleja de la realidad en ~1.2 puntos (escala 1-10)\n- R² ≈ 0.26: el modelo explica ~26% de la varianza de la satisfacción\n:::\n:::\n\n# Parte 3: LASSO con tuning {background-color=\"#2d4563\"}\n\n## Definir LASSO + grilla de búsqueda\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# LASSO: linear_reg con mixture = 1 (L1 puro)\n# tune() = \"este valor se busca con CV\"\nmodelo_lasso <- linear_reg(penalty = tune(), mixture = 1) |>\n  set_engine(\"glmnet\") |>\n  set_mode(\"regression\")\n\nwf_lasso <- workflow() |> add_recipe(receta) |> add_model(modelo_lasso)\n\n# Grilla de 30 valores de λ en escala logarítmica (10^-4 = 0.0001 a 10^0 = 1)\ngrilla_lambda <- grid_regular(penalty(range = c(-4, 0)), levels = 30)\n\nhead(grilla_lambda)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 1\n   penalty\n     <dbl>\n1 0.0001  \n2 0.000137\n3 0.000189\n4 0.000259\n5 0.000356\n6 0.000489\n```\n\n\n:::\n:::\n\n\n- `mixture = 1` → LASSO puro. Si fuera `0`, sería Ridge (lo ven en el Ejercicio 1)\n- `tune()` deja `penalty` (λ) pendiente: lo elige la validación cruzada\n:::\n\n## Tuning de LASSO con CV\n\n:::{style=\"margin-top: 30px; font-size: 19px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Crear folds (10-fold CV)\nfolds <- vfold_cv(datos_train, v = 10)\n\n# Tuning: probar cada valor de la grilla con CV\nresultados_lasso <- tune_grid(\n  wf_lasso,\n  resamples = folds,\n  grid      = grilla_lambda,\n  metrics   = metric_set(rmse)\n)\n\n# Top 5 mejores λ por RMSE\nresultados_lasso |>\n  collect_metrics() |>\n  filter(.metric == \"rmse\") |>\n  arrange(mean) |>\n  head(5) |>\n  knitr::kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n| penalty|.metric |.estimator |   mean|  n| std_err|.config          |\n|-------:|:-------|:----------|------:|--:|-------:|:----------------|\n|  0.0304|rmse    |standard   | 1.2213| 10|  0.0538|pre0_mod19_post0 |\n|  0.0418|rmse    |standard   | 1.2215| 10|  0.0552|pre0_mod20_post0 |\n|  0.0221|rmse    |standard   | 1.2225| 10|  0.0527|pre0_mod18_post0 |\n|  0.0161|rmse    |standard   | 1.2233| 10|  0.0519|pre0_mod17_post0 |\n|  0.0117|rmse    |standard   | 1.2241| 10|  0.0513|pre0_mod16_post0 |\n\n\n:::\n:::\n\n\n- `mean` es el RMSE promedio sobre los 10 folds; `std_err` indica cuánto varía entre folds\n:::\n\n## Visualizar el tuning de LASSO\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nautoplot(resultados_lasso) +\n  scale_x_log10() +\n  theme_minimal() +\n  labs(title = \"RMSE vs. λ (escala log)\")\n```\n\n::: {.cell-output-display}\n![](08-laboratorio-04_files/figure-revealjs/lasso-viz-1.png){fig-align='center' width=2700}\n:::\n:::\n\n\n- La curva suele tener forma de **U**: λ muy bajo → poca regularización (sobreajuste); λ muy alto → demasiada (subajuste)\n- El mínimo de la curva es el λ óptimo según CV\n:::\n\n## Seleccionar λ y ajuste final\n\n:::{style=\"margin-top: 30px; font-size: 18px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Seleccionar el λ con menor RMSE\nlambda_min <- select_best(resultados_lasso, metric = \"rmse\")\n\n# 2. Finalizar el workflow con ese λ y ajustar a todo el train\najuste_lasso <- wf_lasso |>\n  finalize_workflow(lambda_min) |>\n  fit(data = datos_train)\n\n# Métricas en test (las reutilizamos en la tabla comparativa)\npred_lasso     <- augment(ajuste_lasso, datos_test)\nmetricas_lasso <- pred_lasso |>\n  metrics(truth = satisfaccion_vida, estimate = .pred)\n\n# 3. Coeficientes y conteo de variables eliminadas\ncoef_lasso <- tidy(ajuste_lasso) |>\n  filter(term != \"(Intercept)\") |>\n  arrange(desc(abs(estimate)))\n\ncat(\"Variables eliminadas (coef = 0):\",\n    sum(coef_lasso$estimate == 0), \"de\", nrow(coef_lasso), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVariables eliminadas (coef = 0): 3 de 12 \n```\n\n\n:::\n\n```{.r .cell-code}\ncoef_lasso |> head(8) |> knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term                    | estimate| penalty|\n|:-----------------------|--------:|-------:|\n|educacion_anios         |    0.359|    0.03|\n|confianza_gobierno      |    0.233|    0.03|\n|satisfaccion_democracia |    0.230|    0.03|\n|ingreso_hogar           |    0.199|    0.03|\n|percepcion_economia     |    0.185|    0.03|\n|edad                    |    0.154|    0.03|\n|interes_politica        |    0.098|    0.03|\n|uso_internet_diario     |   -0.052|    0.03|\n\n\n:::\n:::\n\n:::\n\n## Comparar coeficientes OLS vs. LASSO\n\n:::{style=\"margin-top: 30px; font-size: 19px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef_ols  <- tidy(ajuste_ols)   |> filter(term != \"(Intercept)\") |>\n             select(term, OLS   = estimate)\ncoef_lasc <- tidy(ajuste_lasso) |> filter(term != \"(Intercept)\") |>\n             select(term, LASSO = estimate)\n\nleft_join(coef_ols, coef_lasc, by = \"term\") |>\n  pivot_longer(c(OLS, LASSO), names_to = \"modelo\", values_to = \"coef\") |>\n  ggplot(aes(x = reorder(term, abs(coef)), y = coef, fill = modelo)) +\n  geom_col(position = \"dodge\") + coord_flip() +\n  scale_fill_manual(values = c(\"OLS\" = \"#3498DB\", \"LASSO\" = \"#E74C3C\")) +\n  labs(title = \"Coeficientes: OLS vs. LASSO\",\n       x = NULL, y = \"Coeficiente (normalizado)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](08-laboratorio-04_files/figure-revealjs/comparar-coef-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n- Es la versión práctica de \"interpretar los coeficientes de LASSO\" que vimos en la clase: LASSO encoge coeficientes hacia cero (algunos exactamente cero); OLS los deja todos sin restricción\n:::\n\n# Parte 4: Ridge por analogía {background-color=\"#2d4563\"}\n\n## Ejercicio 1: Implementar Ridge por analogía {#sec:exercise01}\n\n:::{style=\"margin-top: 30px; font-size: 18px;\"}\n\n**Tarea (5 min):** adapten el pipeline de LASSO que acabamos de ver. Cambia solo lo necesario para Ridge: completen los tres huecos\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Modelo Ridge: igual que LASSO pero mixture = 0\nmodelo_ridge <- linear_reg(penalty = tune(), mixture = ___) |>  # TODO: ¿qué valor?\n  set_engine(\"glmnet\") |>\n  set_mode(\"regression\")\n\n# 2. Workflow + tuning (reutilizamos folds y grilla_lambda)\nwf_ridge <- workflow() |> add_recipe(receta) |> add_model(modelo_ridge)\n\nresultados_ridge <- tune_grid(\n  ___, resamples = folds, grid = grilla_lambda,    # TODO: ¿qué workflow?\n  metrics = metric_set(rmse)\n)\n\n# 3. Seleccionar mejor λ, finalizar, ajustar\nlambda_ridge <- select_best(___, metric = \"rmse\")  # TODO: ¿qué resultados?\najuste_ridge <- finalize_workflow(wf_ridge, lambda_ridge) |>\n  fit(data = datos_train)\n\n# 4. Evaluar en test\npred_ridge     <- augment(ajuste_ridge, datos_test)\nmetricas_ridge <- pred_ridge |>\n  metrics(truth = satisfaccion_vida, estimate = .pred)\n\n# 5. Contar variables eliminadas (debería ser 0!)\ncat(\"Variables eliminadas en Ridge:\",\n    sum(tidy(ajuste_ridge)$estimate[-1] == 0), \"\\n\")\nmetricas_ridge\n```\n:::\n\n\n\n\n:::{.callout-note}\n**Pista**: el único cambio conceptual respecto a LASSO es `mixture = 0`. Los objetos `folds` y `grilla_lambda` ya están definidos; reutilícenlos tal cual\n:::\n\n:::{.callout-tip}\n**Checkpoint**: Ridge debería eliminar **0 variables** (puede mostrar valores como `1e-10`, prácticamente cero pero no exactos). RMSE similar a LASSO (~1.1-1.3)\n:::\n\n[[Apéndice 1: Solución]{.button}](#sec:appendix01)\n:::\n\n## LASSO selecciona, Ridge encoge {#sec:lasso-vs-ridge}\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=50%}\n**LASSO (L1)**\n\n- Penaliza la suma de [valores absolutos]{.alert}\n- Reduce algunos coeficientes a [exactamente cero]{.alert}\n- Hace [selección automática]{.alert} de variables\n- Útil cuando solo algunas variables importan\n:::\n\n:::{.column width=50%}\n**Ridge (L2)**\n\n- Penaliza la suma de [cuadrados]{.alert}\n- Reduce todos los coeficientes pero ninguno a cero exacto\n- [Mantiene todas las variables]{.alert}\n- Útil con variables correlacionadas (multicolinealidad)\n:::\n:::\n\n<br>\n\n[Geométricamente: la \"bola\" de L1 tiene esquinas que tocan los ejes (coeficiente = 0); la \"bola\" de L2 es lisa y nunca toca exactamente un eje.]{.alert}\n\nPara una versión intermedia (Elastic Net), ver [[Apéndice 5]{.button}](#sec:appendix05)\n:::\n\n# Parte 5: Comparación final {background-color=\"#2d4563\"}\n\n## Tabla comparativa: OLS, LASSO y Ridge\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Combinar las métricas de los 3 modelos (ya creadas en los slides anteriores)\ntabla_final <- bind_rows(\n  metricas_ols   |> mutate(modelo = \"OLS\"),\n  metricas_lasso |> mutate(modelo = \"LASSO\"),\n  metricas_ridge |> mutate(modelo = \"Ridge\")\n) |>\n  select(modelo, .metric, .estimate) |>\n  pivot_wider(names_from = .metric, values_from = .estimate) |>\n  arrange(rmse)\n\ntabla_final |> knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|modelo |  rmse|   rsq|   mae|\n|:------|-----:|-----:|-----:|\n|LASSO  | 1.181| 0.273| 0.940|\n|Ridge  | 1.183| 0.269| 0.944|\n|OLS    | 1.190| 0.264| 0.945|\n\n\n:::\n:::\n\n\n- Los 3 modelos producen RMSE muy similares en este dataset\n- LASSO selecciona variables; Ridge las encoge; OLS no penaliza\n:::\n\n## Ejercicio 2: ¿Predicción o explicación? {#sec:exercise02}\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\n**Tarea (5 min):** miren la tabla comparativa y el gráfico de coeficientes OLS vs. LASSO, y discutan en grupo\n\n1. ¿Qué variables redujo LASSO a cero? ¿Tiene sentido sustantivo que esas pesen menos?\n2. Si el objetivo es [explicar]{.alert} qué determina la satisfacción con la vida, ¿qué modelo prefieren? ¿Y si solo quieren [predecirla]{.alert} para casos nuevos?\n3. ¿Por qué las diferencias de RMSE entre los tres modelos son tan pequeñas con estos datos?\n\n:::{.callout-note}\n**Pista**: vuelvan a la distinción de la clase entre [predicción]{.alert} y [explicación]{.alert}. Un modelo más simple (menos variables) es más fácil de explicar, aunque prediga casi igual\n:::\n\n[[Apéndice 2: Discusión]{.button}](#sec:appendix02)\n:::\n\n# Cierre {background-color=\"#2d4563\"}\n\n## Discusión y resumen {#sec:discussion}\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=50%}\n**Lo que vimos hoy:**\n\n1. Ejecutar la receta completa: `receta` → modelo → `workflow`\n2. Tunear LASSO con CV y seleccionar λ\n3. Implementar Ridge por analogía (Ejercicio 1)\n4. Comparar OLS, LASSO y Ridge\n5. Decidir entre predicción y explicación (Ejercicio 2)\n:::\n\n:::{.column width=50%}\n**Conceptos clave:**\n\n- `mixture = 1` → [LASSO]{.alert} (selecciona)\n- `mixture = 0` → [Ridge]{.alert} (encoge)\n- `tune()` + `tune_grid()` para CV\n- `select_best()` + `finalize_workflow()` para fijar λ\n- En este dataset las diferencias entre OLS/LASSO/Ridge son [marginales]{.alert}\n:::\n:::\n\n<br>\n\n[¿Por qué tan marginales? Porque las relaciones son aproximadamente lineales y el ratio n/p no es extremo. La regularización brilla cuando p ≫ n o hay colinealidad fuerte.]{.alert}\n\nPara llevarse a casa: en el [[Apéndice 4]{.button}](#sec:appendix04) apliquen todo el pipeline a un outcome diferente (`satisfaccion_democracia`)\n:::\n\n# Apéndice: Soluciones {background-color=\"#2d4563\"}\n\n## Apéndice 1: Solución Ejercicio 1 {#sec:appendix01}\n\n:::{style=\"margin-top: 20px; font-size: 18px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Cambio único: mixture = 0 (Ridge en vez de LASSO)\nmodelo_ridge <- linear_reg(penalty = tune(), mixture = 0) |>\n  set_engine(\"glmnet\") |>\n  set_mode(\"regression\")\n\nwf_ridge <- workflow() |> add_recipe(receta) |> add_model(modelo_ridge)\n\nresultados_ridge <- tune_grid(\n  wf_ridge, resamples = folds, grid = grilla_lambda,\n  metrics = metric_set(rmse)\n)\n\nlambda_ridge <- select_best(resultados_ridge, metric = \"rmse\")\najuste_ridge <- finalize_workflow(wf_ridge, lambda_ridge) |>\n  fit(data = datos_train)\n\npred_ridge     <- augment(ajuste_ridge, datos_test)\nmetricas_ridge <- pred_ridge |>\n  metrics(truth = satisfaccion_vida, estimate = .pred)\n\ncat(\"Variables eliminadas en Ridge:\",\n    sum(tidy(ajuste_ridge)$estimate[-1] == 0), \"\\n\")\nmetricas_ridge\n```\n:::\n\n\n**Métricas de Ridge en test:**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|.metric |.estimator | .estimate|\n|:-------|:----------|---------:|\n|rmse    |standard   |     1.183|\n|rsq     |standard   |     0.269|\n|mae     |standard   |     0.944|\n\n\n:::\n:::\n\n\n- Ridge nunca elimina variables, solo las encoge; el conteo de eliminadas es 0\n- RMSE similar al de LASSO en este dataset\n\n[[Volver al ejercicio]{.button}](#sec:exercise01)\n:::\n\n## Apéndice 2: Discusión Ejercicio 2 {#sec:appendix02}\n\n:::{style=\"margin-top: 20px; font-size: 20px;\"}\n\n**No hay una única respuesta correcta. Algunas ideas:**\n\n- **Variables eliminadas:** LASSO suele llevar a cero las de menor señal en estos datos (por ejemplo algunas dummies de `zona` o `genero`). Que pesen poco es plausible: no son los grandes determinantes de la satisfacción\n- **¿Explicar o predecir?** Si el objetivo es [explicar]{.alert}, conviene un modelo simple e interpretable: OLS o LASSO (LASSO además deja una lista corta de variables). Si el objetivo es [predecir]{.alert} casos nuevos, elegimos por RMSE en test, sin importar cuántas variables queden\n- **Diferencias pequeñas de RMSE:** con relaciones casi lineales y `n` mayor que el número de predictores, hay poco sobreajuste que corregir. La regularización aporta más cuando hay muchas variables o colinealidad fuerte\n\n[[Volver al ejercicio]{.button}](#sec:exercise02)\n:::\n\n## Apéndice 3: Dos criterios para elegir λ (opcional) {#sec:appendix03}\n\n:::{style=\"margin-top: 20px; font-size: 19px;\"}\n\nEn la clase vimos dos formas de elegir λ. Hasta ahora usamos `select_best` (mínimo RMSE). La regla [1-SE]{.alert} elige el λ más grande (modelo más simple) que queda a menos de un error estándar del mínimo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Criterio 1: mínimo RMSE (el que usamos en el lab)\nlambda_min  <- select_best(resultados_lasso, metric = \"rmse\")\n\n# Criterio 2: regla de un error estándar (modelo más parsimonioso)\nlambda_1se  <- select_by_one_std_err(resultados_lasso, metric = \"rmse\", desc(penalty))\n\nbind_rows(\n  lambda_min |> mutate(criterio = \"min\"),\n  lambda_1se |> mutate(criterio = \"1-SE\")\n)\n```\n:::\n\n\n- `lambda_1se` suele ser mayor, así que regulariza más y deja menos variables\n- Sacrifica un poco de RMSE a cambio de un modelo más simple de explicar\n\n[[Volver a la sección de discusión]{.button}](#sec:discussion)\n:::\n\n## Apéndice 4: Capstone: outcome diferente (opcional) {#sec:appendix04}\n\n:::{style=\"margin-top: 20px; font-size: 17px;\"}\n\n**Para llevarse a casa:** apliquen todo el pipeline a `satisfaccion_democracia` (escala 1-5). ¿Cómo cambian los resultados?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Nueva receta para predecir satisfaccion_democracia\nreceta_dem <- recipe(satisfaccion_democracia ~ ., data = datos_train) |>\n  step_rm(pais, voto, satisfaccion_vida) |>      # excluir outcomes ajenos\n  step_dummy(all_nominal_predictors()) |>\n  step_normalize(all_numeric_predictors()) |>\n  step_zv(all_predictors())\n\n# 2. LASSO con la nueva receta (mismo patrón)\nwf_lasso_dem <- workflow() |> add_recipe(receta_dem) |> add_model(modelo_lasso)\n\nresultados_dem <- tune_grid(\n  wf_lasso_dem, resamples = folds, grid = grilla_lambda,\n  metrics = metric_set(rmse)\n)\n\nlambda_dem  <- select_best(resultados_dem, metric = \"rmse\")\najuste_dem  <- finalize_workflow(wf_lasso_dem, lambda_dem) |>\n  fit(data = datos_train)\n\n# 3. Evaluación\npred_dem <- augment(ajuste_dem, datos_test)\n\npred_dem |> metrics(truth = satisfaccion_democracia, estimate = .pred)\n```\n:::\n\n\nPreguntas para reflexionar:\n\n- ¿Las mismas variables son predictivas, o cambian?\n- ¿El RMSE es mayor o menor que para `satisfaccion_vida`?\n- Pueden repetir con `percepcion_economia` como tercer outcome\n\n[[Volver a la sección de discusión]{.button}](#sec:discussion)\n:::\n\n## Apéndice 5: Elastic Net (opcional) {#sec:appendix05}\n\n:::{style=\"margin-top: 20px; font-size: 18px;\"}\n\nElastic Net combina LASSO y Ridge: `mixture` entre 0 y 1\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Ajustar AMBOS hiperparámetros: penalty (λ) y mixture (α)\nmodelo_enet <- linear_reg(penalty = tune(), mixture = tune()) |>\n  set_engine(\"glmnet\") |>\n  set_mode(\"regression\")\n\nwf_enet <- workflow() |> add_recipe(receta) |> add_model(modelo_enet)\n\n# Grilla 2D: 15 valores de λ × 5 de mixture\ngrilla_enet <- grid_regular(\n  penalty(range = c(-4, 0)),\n  mixture(range = c(0, 1)),\n  levels = c(15, 5)\n)\n\nresultados_enet <- tune_grid(\n  wf_enet, resamples = folds, grid = grilla_enet,\n  metrics = metric_set(rmse)\n)\n\nmejor_enet  <- select_best(resultados_enet, metric = \"rmse\")\nmejor_enet  # vean el mixture óptimo\n\najuste_enet <- finalize_workflow(wf_enet, mejor_enet) |>\n  fit(data = datos_train)\n\npredict(ajuste_enet, datos_test) |>\n  bind_cols(datos_test |> select(satisfaccion_vida)) |>\n  metrics(truth = satisfaccion_vida, estimate = .pred)\n```\n:::\n\n\n- Si `mixture` óptimo está cerca de 1 → LASSO ganó\n- Si está cerca de 0 → Ridge ganó\n- Si intermedio → Elastic Net mejora sobre ambos\n\n[[Volver a la sección de LASSO vs. Ridge]{.button}](#sec:lasso-vs-ridge)\n:::\n\n# Fin del día 2! 🤓 {background-color=\"#2d4563\"}\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}