{
  "hash": "42d848eac5569495dc938b22e9f817e9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"IA para Científicos Sociales\"\nsubtitle: \"Sesión 3.3: Laboratorio 5 - Clustering y PCA\"\nauthor:\n  - name: Danilo Freire\n    orcid: 0000-0002-4712-6810\n    email: danilofreire@gmail.com\n    affiliations: \"Department of Data and Decision Sciences <br> Emory University\"\nformat:\n  clean-revealjs:\n    self-contained: true\n    footer: \"[Sesión 3.3](https://danilofreire.github.io/introduccion-ia-ucu/clases/dia-03/11-laboratorio-05.html)\"\n    transition: slide\n    transition-speed: default\n    scrollable: true\nrevealjs-plugins:\n  - multimodal\nengine: knitr\neditor:\n  render-on-save: true\nlang: es\n---\n\n\n\n# Laboratorio 5: Clustering y PCA {background-color=\"#2d4563\"}\n\n## Objetivos del laboratorio\n\n:::{style=\"margin-top: 30px; font-size: 26px;\"}\n:::{.columns}\n:::{.column width=50%}\n**Lo que vamos a hacer:**\n\n1. Explorar 8 indicadores de 18 países\n2. Aplicar K-means y evaluar clusters\n3. Usar el método del codo y silueta\n4. Ejecutar PCA e interpretar componentes\n5. Visualizar con biplot\n:::\n\n:::{.column width=50%}\n**Lo que queremos descubrir:**\n\n- ¿Qué países se parecen entre sí?\n- ¿Cuántos grupos distintos hay?\n- ¿Qué dimensiones ocultas resumen las 8 variables?\n- ¿Es el [desarrollo]{.alert} una sola cosa o varias?\n:::\n:::\n\n<br>\n\n[Trabajen en sus computadoras. Intenten resolver los ejercicios antes de mirar la solución. Clustering jerárquico y ejercicios adicionales están en los apéndices]{.alert}\n:::\n\n# Parte 1: Exploración de datos {background-color=\"#2d4563\"}\n\n## Cargar paquetes\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Instala los que falten y los carga\nR> paquetes <- c(\n+   \"tidyverse\",\n+   \"tidymodels\",   # recipe(), step_normalize()\n+   \"cluster\",      # silhouette()\n+   \"factoextra\",   # fviz_cluster(), fviz_nbclust(), fviz_pca(), ...\n+   \"corrplot\"      # matriz de correlación\n+ )\nR> for (pkg in paquetes) {\n+   if (!require(pkg, character.only = TRUE)) {\n+     install.packages(pkg, dependencies = TRUE)\n+     library(pkg, character.only = TRUE)\n+   }\n+ }\nR> \nR> set.seed(2026)\n```\n:::\n\n:::\n\n## Cargar y explorar los datos\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Cargar indicadores por país\nR> paises <- read_csv(\"datos/indicadores_paises.csv\")\nR> # Lean el archivo directo desde la web:\nR> # paises <- read_csv(\"https://raw.githubusercontent.com/danilofreire/introduccion-ia-ucu/main/clases/dia-03/datos/indicadores_paises.csv\")\nR> \nR> # Vista general\nR> glimpse(paises)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 18\nColumns: 9\n$ pais              <chr> \"Argentina\", \"Bolivia\", \"Brasil\", \"Chile\", \"Colombia…\n$ pib_per_capita    <dbl> 10756, 3276, 8942, 15375, 5900, 11745, 5979, 4094, 5…\n$ esperanza_vida    <dbl> 76.3, 71.7, 75.8, 80.2, 76.9, 80.7, 77.0, 73.7, 74.6…\n$ anios_educacion   <dbl> 10.7, 8.8, 8.1, 10.1, 8.1, 8.9, 8.1, 7.1, 5.4, 6.9, …\n$ acceso_internet   <dbl> 86.5, 53.2, 80.1, 87.3, 73.1, 80.2, 64.2, 50.7, 44.3…\n$ gasto_salud_pib   <dbl> 10.3, 6.7, 9.7, 9.1, 8.1, 8.0, 8.2, 7.4, 5.6, 7.7, 5…\n$ indice_gini       <dbl> 41.3, 44.3, 48.7, 45.4, 50.4, 48.1, 44.9, 38.6, 47.8…\n$ urbanizacion      <dbl> 91.7, 69.8, 86.7, 87.3, 81.3, 81.0, 64.0, 73.3, 51.7…\n$ indice_democracia <dbl> 6.7, 4.4, 7.0, 8.1, 7.0, 8.3, 5.7, 5.8, 4.9, 5.4, 5.…\n```\n\n\n:::\n:::\n\n:::\n\n## Variables del dataset\n\n:::{style=\"margin-top: 30px; font-size: 26px;\"}\n\n| Variable | Descripción |\n|----------|-------------|\n| `pib_per_capita` | PIB per cápita en USD |\n| `esperanza_vida` | Esperanza de vida al nacer (años) |\n| `anios_educacion` | Años promedio de escolaridad |\n| `acceso_internet` | % de población con acceso a internet |\n| `gasto_salud_pib` | Gasto en salud como % del PIB |\n| `indice_gini` | Índice de Gini (desigualdad, 0-100) |\n| `urbanizacion` | % de población urbana |\n| `indice_democracia` | Índice de democracia (0-10) |\n\n:::{style=\"text-align: center;\"}\n[Todas las variables son numéricas. Ideal para clustering y PCA]{.alert}\n:::\n:::\n\n## Estadísticas descriptivas\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Resumen de cada variable\nR> paises |>\n+   select(-pais) |>\n+   summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n pib_per_capita  esperanza_vida  anios_educacion  acceso_internet\n Min.   : 1881   Min.   :71.70   Min.   : 5.400   Min.   :30.30  \n 1st Qu.: 4329   1st Qu.:74.22   1st Qu.: 7.725   1st Qu.:55.70  \n Median : 6108   Median :75.55   Median : 8.300   Median :71.00  \n Mean   : 7971   Mean   :75.87   Mean   : 8.406   Mean   :66.39  \n 3rd Qu.:10636   3rd Qu.:76.97   3rd Qu.: 8.975   3rd Qu.:78.80  \n Max.   :17185   Max.   :80.70   Max.   :10.700   Max.   :88.20  \n gasto_salud_pib   indice_gini     urbanizacion   indice_democracia\n Min.   : 4.200   Min.   :38.60   Min.   :51.70   Min.   :2.100    \n 1st Qu.: 5.875   1st Qu.:42.58   1st Qu.:65.17   1st Qu.:5.425    \n Median : 7.550   Median :45.50   Median :79.70   Median :6.350    \n Mean   : 7.383   Mean   :45.29   Mean   :75.66   Mean   :6.061    \n 3rd Qu.: 8.275   3rd Qu.:48.02   3rd Qu.:85.72   3rd Qu.:6.925    \n Max.   :10.300   Max.   :52.30   Max.   :95.00   Max.   :8.700    \n```\n\n\n:::\n:::\n\n\nLas variables tienen [escalas muy diferentes]{.alert} (PIB en miles vs. índices de 0-10). Es necesario escalar antes de aplicar K-means o PCA\n:::\n\n## Matriz de correlación\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Calcular correlaciones\nR> cor_matrix <- paises |>\n+   select(-pais) |>\n+   cor()\nR> \nR> # Visualizar\nR> corrplot(cor_matrix, method = \"color\", type = \"upper\",\n+          addCoef.col = \"black\", number.cex = 0.7,\n+          tl.col = \"black\", tl.srt = 45,\n+          col = colorRampPalette(c(\"#E74C3C\", \"white\", \"#2d4563\"))(200))\n```\n\n::: {.cell-output-display}\n![](11-laboratorio-05_files/figure-revealjs/correlacion-1.png){fig-align='center' width=1950}\n:::\n:::\n\n:::\n\n## Interpretación de correlaciones\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n:::{.columns}\n:::{.column width=50%}\n**Correlaciones positivas fuertes:**\n\n- Internet ↔ urbanización: **0.86**\n- Esperanza de vida ↔ democracia: **0.77**\n- PIB ↔ democracia: **0.76**\n- PIB ↔ esperanza de vida: **0.74**\n- PIB ↔ internet: **0.73**\n- Internet ↔ educación: **0.67**\n\nEstas variables \"van juntas\": los países con mayor PIB tienen mejor educación, salud, democracia e internet\n:::\n\n:::{.column width=50%}\n**Correlaciones negativas:**\n\n- Gini ↔ urbanización: **-0.41**\n- Gini ↔ internet: **-0.26**\n- Gini ↔ PIB: **-0.15**\n\nLos países más desiguales tienden a ser menos urbanos y con menor acceso a internet. La correlación Gini ↔ democracia es **-0.12**, casi nula\n\n<br>\n\n[Varias variables \"apuntan en la misma dirección\": el PCA las resumirá en un \"eje de desarrollo\"]{.alert}\n:::\n:::\n:::\n\n## Ejercicio rápido: dos países {#sec:ejercicio-paises}\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n\nElijan dos países del dataset que les interesen (por ejemplo, Uruguay vs. Honduras, Chile vs. Bolivia, o Argentina vs. Venezuela). Comparen sus valores en las 8 variables.\n\n**Preguntas:**\n\n- ¿Cuál parece más [desarrollado]{.alert}?\n- ¿En qué variable es mayor la diferencia?\n- ¿Hay alguna variable en la que el \"menos desarrollado\" supere al otro?\n\n*Pista:* usen `paises |> filter(pais %in% c(\"...\", \"...\"))` y `select()` con las variables que quieran comparar.\n\n[Tómense 3 minutos para experimentar]{.alert}\n\n[[Apéndice: Solución]{.button}](#sec:sol-paises)\n:::\n\n## Preparar datos para clustering\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Escalar con una receta (media = 0, sd = 1), como en el Día 2\nR> receta_paises <- recipe(~ ., data = paises) |>\n+   update_role(pais, new_role = \"id\") |>\n+   step_normalize(all_numeric_predictors())\nR> \nR> datos_scaled <- receta_paises |> prep() |> juice() |>\n+   column_to_rownames(\"pais\")\nR> \nR> head(datos_scaled, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          pib_per_capita esperanza_vida anios_educacion acceso_internet\nArgentina      0.5937295     0.17882893       1.6006861       1.1829170\nBolivia       -1.0007920    -1.71950893       0.2751785      -0.7762995\nBrasil         0.2070367    -0.02751214      -0.2131664       0.8063709\nChile          1.5783679     1.78828929       1.1821047       1.2299853\nColombia      -0.4414304     0.42643822      -0.2131664       0.3945236\n          gasto_salud_pib indice_gini urbanizacion indice_democracia\nArgentina       1.6825368 -1.01330353    1.2641504         0.3835748\nBolivia        -0.3941943 -0.25226889   -0.4613624        -0.9972946\nBrasil          1.3364149  0.86391525    0.8701977         0.5636882\nChile           0.9902931  0.02677714    0.9174721         1.2241040\nColombia        0.4134233  1.29516821    0.4447288         0.5636882\n```\n\n\n:::\n:::\n\n\n[`step_normalize()`]{.alert} hace lo mismo que `scale()` y es la sintaxis que ya usamos en los laboratorios del Día 2. La receta [no tiene variable objetivo]{.alert} (empieza con `~`) y `update_role()` marca a `pais` como identificador, no como variable a normalizar\n\n[`column_to_rownames(\"pais\")`]{.alert} mueve la columna `pais` a los nombres de fila, así los nombres de países se preservan automáticamente en todos los plots posteriores (clusters, dendrograma, biplot)\n:::\n\n# Parte 2: K-means y evaluación {background-color=\"#2d4563\"}\n\n## ¿Qué buscamos con el clustering?\n\n:::{style=\"margin-top: 30px; font-size: 26px;\"}\n\nLa [hipótesis]{.alert}: los 18 países latinoamericanos no son todos iguales en desarrollo. K-means los dividirá en grupos \"parecidos entre sí\".\n\n**Preguntas que queremos responder:**\n\n- ¿Cuántos grupos realmente distintos hay? (¿2, 3, 4?)\n- ¿Qué países entran en cada grupo?\n- ¿Los grupos corresponden a niveles de desarrollo, o a otra dimensión?\n- ¿El resultado es estable o sensible al número K elegido?\n\n[Métrica de éxito:]{.alert} que los grupos tengan sentido sustantivo (países parecidos juntos) y que lo confirmen métricas como la [silueta]{.alert} y el [método del codo]{.alert}\n:::\n\n## Ejecutar K-means con K=2\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # K-means con 2 clusters\nR> km2 <- kmeans(datos_scaled, centers = 2, nstart = 25)\nR> \nR> # Ver resultados\nR> km2$cluster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Argentina              Bolivia               Brasil \n                   1                    2                    1 \n               Chile             Colombia           Costa Rica \n                   1                    1                    1 \n             Ecuador          El Salvador            Guatemala \n                   2                    2                    2 \n            Honduras               México            Nicaragua \n                   2                    2                    2 \n              Panamá             Paraguay                 Perú \n                   1                    2                    2 \nRepública Dominicana              Uruguay            Venezuela \n                   2                    1                    2 \n```\n\n\n:::\n\n```{.r .cell-code}\nR> # Agregar al dataframe original\nR> paises$cluster_km2 <- factor(km2$cluster)\n```\n:::\n\n:::\n\n## Visualizar los clusters\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Visualización con factoextra (usa PCA automáticamente)\nR> fviz_cluster(km2, data = datos_scaled,\n+              palette = c(\"#2d4563\", \"#e63946\"),\n+              geom = \"point\",\n+              ellipse.type = \"convex\",\n+              ggtheme = theme_minimal()) +\n+   geom_text(aes(label = rownames(datos_scaled)), vjust = -1, size = 3) +\n+   labs(title = \"K-means con K=2\")\n```\n\n::: {.cell-output-display}\n![](11-laboratorio-05_files/figure-revealjs/viz-kmeans-1.png){fig-align='center' width=2400}\n:::\n:::\n\n:::\n\n## ¿Qué países están en cada cluster?\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Listar países por cluster\nR> paises |>\n+   group_by(cluster_km2) |>\n+   summarise(paises = paste(pais, collapse = \", \"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  cluster_km2 paises                                                            \n  <fct>       <chr>                                                             \n1 1           Argentina, Brasil, Chile, Colombia, Costa Rica, Panamá, Uruguay   \n2 2           Bolivia, Ecuador, El Salvador, Guatemala, Honduras, México, Nicar…\n```\n\n\n:::\n:::\n\n:::\n\n## Perfil de cada cluster\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Medias por cluster (datos originales, no escalados)\nR> paises |>\n+   group_by(cluster_km2) |>\n+   summarise(\n+     n = n(),\n+     pib_mean = round(mean(pib_per_capita)),\n+     vida_mean = round(mean(esperanza_vida), 1),\n+     educ_mean = round(mean(anios_educacion), 1),\n+     inet_mean = round(mean(acceso_internet), 1),\n+     gini_mean = round(mean(indice_gini), 1),\n+     demo_mean = round(mean(indice_democracia), 1)\n+   )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 8\n  cluster_km2     n pib_mean vida_mean educ_mean inet_mean gini_mean demo_mean\n  <fct>       <int>    <dbl>     <dbl>     <dbl>     <dbl>     <dbl>     <dbl>\n1 1               7    12234      78         9.2      79.8      46.1       7.5\n2 2              11     5258      74.5       7.9      57.9      44.8       5.1\n```\n\n\n:::\n:::\n\n\n¿Los dos clusters corresponden a \"más desarrollados\" vs. \"menos desarrollados\"? ¿En qué variable se diferencian más?\n:::\n\n## Método del codo\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Calcular WSS para K=1 a K=8\nR> fviz_nbclust(datos_scaled, kmeans,\n+              method = \"wss\",\n+              k.max = 8,\n+              nstart = 25) +\n+   labs(title = \"Método del codo\",\n+        subtitle = \"¿Dónde se 'aplana' la curva?\") +\n+   theme_minimal()\n```\n\n::: {.cell-output-display}\n![](11-laboratorio-05_files/figure-revealjs/metodo-codo-1.png){fig-align='center' width=1950}\n:::\n:::\n\n\n[La mayor caída va de K=1 a K=2. Después la curva se aplana: K=2 es el codo]{.alert}\n:::\n\n## Método de la silueta\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Calcular silueta promedio para K=2 a K=8\nR> fviz_nbclust(datos_scaled, kmeans,\n+              method = \"silhouette\",\n+              k.max = 8,\n+              nstart = 25) +\n+   labs(title = \"Método de la silueta\",\n+        subtitle = \"K óptimo maximiza la silueta promedio\") +\n+   theme_minimal()\n```\n\n::: {.cell-output-display}\n![](11-laboratorio-05_files/figure-revealjs/metodo-silueta-1.png){fig-align='center' width=1950}\n:::\n:::\n\n\n[El pico está en K=2. Codo y silueta coinciden: dos grupos es la solución más defendible]{.alert}\n:::\n\n## Interpretación de la silueta\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n:::{.columns}\n:::{.column width=50%}\n**Silueta promedio:**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Calcular silueta para cada observación\nR> sil <- silhouette(km2$cluster,\n+                   dist(datos_scaled))\nR>                   \nR> mean(sil[, 3])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2888078\n```\n\n\n:::\n:::\n\n\nUn valor de ~0.29 indica estructura [débil pero visible]{.alert}\n\n**Observaciones con silueta negativa:**\n\nEstán mal clasificadas (más cerca del otro cluster)\n:::\n\n:::{.column width=50%}\n**Regla de interpretación:**\n\n:::{style=\"text-align: center;\"}\n\n| Valor | Significado |\n|-------|-------------|\n| 0.71 - 1.00 | Fuerte |\n| 0.51 - 0.70 | Razonable |\n| 0.26 - 0.50 | Débil |\n| < 0.25 | Sin estructura |\n:::\n\n<br>\n\n[Con solo 18 países, es difícil obtener siluetas muy altas]{.alert}\n:::\n:::\n:::\n\n## Ejercicio rápido: ¿y si probamos K=3? {#sec:ejercicio-k3}\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\nCodo y silueta apuntan a K=2, pero K=3 está muy cerca. Prueben dividir los países en 3 grupos y comparen.\n\n**Instrucciones:**\n\n1. Ejecuten `kmeans(datos_scaled, centers = 3, nstart = 25)` y guárdenlo en `km3`\n2. Calculen la silueta promedio con `silhouette(km3$cluster, dist(datos_scaled))`\n3. Comparen con la silueta de K=2 (≈ 0.29)\n\n**Preguntas:**\n\n- ¿La silueta sube o baja al pasar de K=2 a K=3?\n- ¿Qué países quedan en el cluster \"intermedio\"?\n- ¿Tiene sentido ese cluster como \"desarrollo medio\"?\n\n[Tómense 3 minutos para experimentar]{.alert}\n\n[[Apéndice: Solución]{.button}](#sec:sol-k3)\n:::\n\n# Parte 3: PCA e interpretación {background-color=\"#2d4563\"}\n\n## ¿Qué buscamos con el PCA?\n\n:::{style=\"margin-top: 30px; font-size: 26px;\"}\n\nTenemos 8 variables. PCA las [comprime]{.alert} en pocas dimensiones sin perder mucha información.\n\n**Preguntas que queremos responder:**\n\n- ¿Cuántas dimensiones bastan para resumir las 8 variables?\n- ¿Qué [significa]{.alert} cada dimensión? (¿\"desarrollo\"? ¿\"desigualdad\"? ¿otra cosa?)\n- ¿Qué países están en los extremos de cada eje?\n- ¿Los clusters de K-means se separan cuando los vemos en PC1 y PC2?\n\n[Métrica de éxito:]{.alert} que con 2 o 3 componentes expliquemos >70% de la varianza, y que los ejes tengan una interpretación sustantiva clara\n:::\n\n## Ejecutar PCA\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # PCA sobre datos escalados\nR> pca <- prcomp(datos_scaled)\nR> \nR> # Resumen de varianza explicada\nR> summary(pca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1    PC2    PC3     PC4     PC5    PC6     PC7\nStandard deviation     2.0441 1.2575 0.9618 0.76749 0.57816 0.4060 0.38499\nProportion of Variance 0.5223 0.1977 0.1156 0.07363 0.04178 0.0206 0.01853\nCumulative Proportion  0.5223 0.7200 0.8356 0.90926 0.95104 0.9716 0.99017\n                           PC8\nStandard deviation     0.28043\nProportion of Variance 0.00983\nCumulative Proportion  1.00000\n```\n\n\n:::\n:::\n\n\n[PC1 explica el 52% de la varianza y PC2 el 20%. Entre los dos resumimos el 72% de la información de las 8 variables originales]{.alert}\n:::\n\n## Scree plot\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Varianza explicada por componente\nR> fviz_eig(pca, addlabels = TRUE,\n+          barfill = \"#2d4563\", barcolor = \"#2d4563\") +\n+   labs(title = \"Scree plot: varianza explicada por componente\") +\n+   theme_minimal()\n```\n\n::: {.cell-output-display}\n![](11-laboratorio-05_files/figure-revealjs/scree-plot-1.png){fig-align='center' width=1950}\n:::\n:::\n\n:::\n\n## Loadings: ¿qué mide cada componente?\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Loadings de los primeros 3 componentes\nR> loadings <- pca$rotation[, 1:3] |>\n+   as.data.frame() |>\n+   rownames_to_column(\"variable\") |>\n+   arrange(desc(abs(PC1)))\nR> \nR> loadings\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           variable        PC1         PC2         PC3\n1    pib_per_capita -0.4387072  0.07337917 -0.03316035\n2   acceso_internet -0.4367711 -0.22750314 -0.09784433\n3 indice_democracia -0.4003006  0.28504978  0.27826091\n4      urbanizacion -0.3831576 -0.39134175 -0.02000521\n5    esperanza_vida -0.3651244  0.43128497 -0.09126237\n6   anios_educacion -0.3159903 -0.32026263 -0.53929448\n7   gasto_salud_pib -0.2547500  0.39962818  0.31365683\n8       indice_gini  0.1079509  0.51007697 -0.71690276\n```\n\n\n:::\n:::\n\n:::\n\n## Interpretación de PC1 y PC2\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=50%}\n**PC1 (52% varianza):**\n\nCargas altas (todas negativas) en:\n\n- PIB (-0.44), internet (-0.44)\n- Democracia (-0.40), urbanización (-0.38)\n- Esperanza de vida (-0.37), educación (-0.32)\n\n→ [Eje de desarrollo general]{.alert}\n\nTodas estas variables cargan en la misma dirección (negativa): un país con PC1 muy negativo tiene más PIB, democracia e internet. El signo es arbitrario; lo que importa es que van juntas\n:::\n\n:::{.column width=50%}\n**PC2 (20% varianza):**\n\nCargas altas en:\n\n- Índice de Gini (0.51)\n- Esperanza de vida (0.43)\n- Gasto en salud (0.40)\n\nCargas negativas en:\n\n- Urbanización (-0.39), educación (-0.32)\n\n→ [Contraste desigualdad / urbanización]{.alert}\n\nSepara países desiguales pero con buena salud de países más urbanos y educados\n:::\n:::\n:::\n\n## Ejercicio rápido: ¿qué país está en los extremos? {#sec:ejercicio-pc1}\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\nOrdenen los países por su valor en PC1 para identificar los más \"desarrollados\" y los menos, según esta medida resumen.\n\n**Instrucciones:**\n\n1. Extraigan las coordenadas PC1 y PC2 desde `pca$x[, 1:2]`\n2. Conviertan a `data.frame` y agreguen los nombres de países con `rownames_to_column(\"pais\")`\n3. Ordenen por PC1 con `arrange(PC1)`\n\n**Preguntas:**\n\n- ¿Coincide el ranking con su intuición sobre el desarrollo latinoamericano?\n- ¿Qué país les sorprende más (arriba o abajo)?\n- ¿Qué países están cerca de PC1 = 0, en el \"medio\"?\n\n[Tómense 3 minutos para experimentar]{.alert}\n\n[[Apéndice: Solución]{.button}](#sec:sol-pc1)\n:::\n\n## Biplot\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Biplot con factoextra\nR> fviz_pca_biplot(pca,\n+                 repel = TRUE,  # Evita solapamiento de etiquetas\n+                 col.var = \"#e63946\",\n+                 col.ind = \"#2d4563\",\n+                 label = \"all\") +\n+   labs(title = \"Biplot: países y variables\") +\n+   theme_minimal()\n```\n\n::: {.cell-output-display}\n![](11-laboratorio-05_files/figure-revealjs/biplot-1.png){fig-align='center' width=2400}\n:::\n:::\n\n:::\n\n## Resumen del laboratorio\n\n:::{style=\"margin-top: 30px; font-size: 24px;\"}\n:::{.columns}\n:::{.column width=50%}\n**Lo que practicamos:**\n\n- Exploración y escalado de datos\n- K-means con evaluación (codo, silueta)\n- PCA con interpretación de loadings\n- Biplot para visualizar países y variables\n:::\n\n:::{.column width=50%}\n**Funciones clave:**\n\n- `step_normalize()`: normalizar datos\n- `kmeans()`: clustering\n- `silhouette()`: evaluar clusters\n- `prcomp()`: PCA\n- `fviz_*()`: visualizaciones\n:::\n:::\n\n<br>\n\n[En el próximo laboratorio aplicaremos análisis de texto. En los apéndices: clustering jerárquico y ejercicios adicionales]{.alert}\n:::\n\n# Apéndice: Soluciones de ejercicios rápidos {background-color=\"#2d4563\"}\n\n## Solución: dos países {#sec:sol-paises}\n\n:::{style=\"margin-top: 20px; font-size: 20px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> paises |>\n+   filter(pais %in% c(\"Uruguay\", \"Honduras\")) |>\n+   select(pais, pib = pib_per_capita, internet = acceso_internet,\n+          democracia = indice_democracia, urban = urbanizacion,\n+          gini = indice_gini)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  pais       pib internet democracia urban  gini\n  <chr>    <dbl>    <dbl>      <dbl> <dbl> <dbl>\n1 Honduras  2658     38.7        5.4  58.8  52.3\n2 Uruguay  17185     88.2        8.7  95    38.9\n```\n\n\n:::\n:::\n\n\n- Uruguay tiene PIB per cápita [más de seis veces mayor]{.alert} que Honduras (17 185 vs. 2 658)\n- Uruguay supera a Honduras en internet (88% vs. 39%), democracia (8.7 vs. 5.4) y urbanización (95% vs. 59%)\n- Pero Honduras tiene Gini [más alto]{.alert} (52.3 vs. 38.9): es más desigual\n- El \"desarrollo\" no es una sola cosa: hay variables que van en distintas direcciones\n\n[[Volver al ejercicio]{.button}](#sec:ejercicio-paises)\n:::\n\n## Solución: ¿y si probamos K=3? {#sec:sol-k3}\n\n:::{style=\"margin-top: 20px; font-size: 20px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> km3 <- kmeans(datos_scaled, centers = 3, nstart = 25)\nR> sil3 <- silhouette(km3$cluster, dist(datos_scaled))\nR> mean(sil3[, 3])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2716258\n```\n\n\n:::\n\n```{.r .cell-code}\nR> # ¿Qué países quedan en cada cluster?\nR> data.frame(pais = rownames(datos_scaled), cluster = km3$cluster) |>\n+   arrange(cluster)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                     pais cluster\nBolivia                           Bolivia       1\nEcuador                           Ecuador       1\nEl Salvador                   El Salvador       1\nMéxico                             México       1\nParaguay                         Paraguay       1\nPerú                                 Perú       1\nRepública Dominicana República Dominicana       1\nVenezuela                       Venezuela       1\nGuatemala                       Guatemala       2\nHonduras                         Honduras       2\nNicaragua                       Nicaragua       2\nArgentina                       Argentina       3\nBrasil                             Brasil       3\nChile                               Chile       3\nColombia                         Colombia       3\nCosta Rica                     Costa Rica       3\nPanamá                             Panamá       3\nUruguay                           Uruguay       3\n```\n\n\n:::\n:::\n\n\n- Silueta con K=3: [≈ 0.27]{.alert} (con K=2 era ≈ 0.29, así que baja un poco)\n- El cluster \"intermedio\" suele contener países como Bolivia, Ecuador, México, Perú, Paraguay y República Dominicana: desarrollo medio\n- El cluster \"bajo\" queda como Guatemala, Honduras y Nicaragua: los más pobres\n- [Lección:]{.alert} K=3 tiene sentido sustantivo aunque la silueta sea levemente peor\n\n[[Volver al ejercicio]{.button}](#sec:ejercicio-k3)\n:::\n\n## Solución: ¿qué país está en los extremos? {#sec:sol-pc1}\n\n:::{style=\"margin-top: 20px; font-size: 18px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> pca$x[, 1:2] |>\n+   as.data.frame() |>\n+   rownames_to_column(\"pais\") |>\n+   arrange(PC1) |>\n+   mutate(PC1 = round(PC1, 2), PC2 = round(PC2, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   pais   PC1   PC2\n1               Uruguay -3.45 -0.26\n2                 Chile -3.35  0.63\n3             Argentina -2.52 -0.89\n4            Costa Rica -2.26  1.35\n5                Panamá -1.26  1.03\n6                Brasil -1.17  0.68\n7              Colombia -0.43  0.94\n8                México -0.09 -0.92\n9  República Dominicana -0.02 -1.56\n10                 Perú  0.00 -0.94\n11              Ecuador  0.45  0.70\n12             Paraguay  0.83  0.05\n13          El Salvador  1.33 -0.78\n14            Venezuela  1.37 -2.99\n15              Bolivia  1.97 -1.12\n16             Honduras  2.47  1.87\n17            Guatemala  3.03  1.15\n18            Nicaragua  3.11  1.05\n```\n\n\n:::\n:::\n\n\n- Los valores más negativos de PC1 (Uruguay, Chile, Argentina, Costa Rica, Panamá) son los países más \"desarrollados\" en este conjunto\n- Los valores más positivos (Honduras, Nicaragua, Guatemala) son los menos desarrollados\n- [Sorpresas posibles:]{.alert} Venezuela tiene el PC2 más bajo (-2.99): combina alta urbanización y educación con el menor gasto en salud y la democracia más baja; México sorprende por estar cerca del medio pese a su PIB\n\n[[Volver al ejercicio]{.button}](#sec:ejercicio-pc1)\n:::\n\n# Apéndice 1: Clustering jerárquico {background-color=\"#2d4563\"}\n\n## Calcular distancias y dendrograma\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Matriz de distancias euclidianas\nR> d <- dist(datos_scaled, method = \"euclidean\")\nR> \nR> # Clustering jerárquico con método Ward\nR> hc <- hclust(d, method = \"ward.D2\")\nR> \nR> # Dendrograma con rectángulos para K=2\nR> plot(hc, hang = -1, cex = 0.9,\n+      main = \"Dendrograma: Países latinoamericanos\",\n+      xlab = \"País\", ylab = \"Altura\")\nR> rect.hclust(hc, k = 2, border = c(\"#2d4563\", \"#e63946\"))\n```\n\n::: {.cell-output-display}\n![](11-laboratorio-05_files/figure-revealjs/hclust-basico-1.png){fig-align='center' width=2700}\n:::\n:::\n\n:::\n\n## Cortar y comparar con K-means\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> # Cortar para obtener K=2 clusters\nR> grupos_hc <- cutree(hc, k = 2)\nR> \nR> # Comparar con K-means\nR> table(K_means = km2$cluster, Jerarquico = grupos_hc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Jerarquico\nK_means  1  2\n      1  7  0\n      2  0 11\n```\n\n\n:::\n:::\n\n\nLos números de cluster son arbitrarios (cluster 1 en K-means puede ser cluster 2 en jerárquico). Lo importante es si los grupos de países coinciden\n:::\n\n# Apéndice 2: PCA avanzado {background-color=\"#2d4563\"}\n\n## PCA coloreado por cluster K-means\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> pca_coords <- pca$x[, 1:2] |>\n+   as.data.frame() |>\n+   rownames_to_column(\"pais\") |>\n+   mutate(cluster = paises$cluster_km2)\nR> \nR> ggplot(pca_coords, aes(x = PC1, y = PC2, color = cluster, label = pais)) +\n+   geom_point(size = 3) +\n+   geom_text(vjust = -0.8, size = 3, show.legend = FALSE) +\n+   scale_color_manual(values = c(\"#2d4563\", \"#e63946\")) +\n+   labs(title = \"PCA coloreado por cluster K-means\",\n+        x = paste0(\"PC1 (\", round(summary(pca)$importance[2,1]*100, 1), \"%)\"),\n+        y = paste0(\"PC2 (\", round(summary(pca)$importance[2,2]*100, 1), \"%)\")) +\n+   theme_minimal()\n```\n\n::: {.cell-output-display}\n![](11-laboratorio-05_files/figure-revealjs/pca-cluster-1.png){fig-align='center' width=2400}\n:::\n:::\n\n:::\n\n## Contribución de variables a cada componente\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> fviz_contrib(pca, choice = \"var\", axes = 1, fill = \"#2d4563\") +\n+   labs(title = \"Contribución de variables a PC1\") +\n+   theme_minimal()\n```\n\n::: {.cell-output-display}\n![](11-laboratorio-05_files/figure-revealjs/contrib-var-1.png){fig-align='center' width=2400}\n:::\n:::\n\n:::\n\n# Apéndice 3: Ejercicios adicionales {background-color=\"#2d4563\"}\n\n## Ejercicio: Probar K=4\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n**Instrucciones:**\n\n1. Ejecutar K-means con K=4\n2. Visualizar los clusters\n3. Calcular la silueta\n4. ¿Mejora respecto a K=2?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> km4 <- kmeans(datos_scaled, centers = 4, nstart = 25)\nR> \nR> # Silueta promedio\nR> sil4 <- silhouette(km4$cluster, dist(datos_scaled))\nR> mean(sil4[, 3])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2354994\n```\n\n\n:::\n\n```{.r .cell-code}\nR> # Visualizar\nR> fviz_cluster(km4, data = datos_scaled,\n+              palette = c(\"#2d4563\", \"#e63946\", \"#457b9d\", \"#f4a261\"),\n+              ggtheme = theme_minimal()) +\n+   labs(title = \"K-means con K=4\")\n```\n\n::: {.cell-output-display}\n![](11-laboratorio-05_files/figure-revealjs/ejercicio-1-1.png){fig-align='center' width=2400}\n:::\n:::\n\n:::\n\n## Ejercicio: PCA con 3 componentes\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n\n**Instrucciones:**\n\n1. Extraer los primeros 3 componentes\n2. Comparar PC1-PC2 vs. PC1-PC3\n3. ¿El tercer componente agrega información útil?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nR> pca_3d <- pca$x[, 1:3] |>\n+   as.data.frame() |>\n+   rownames_to_column(\"pais\") |>\n+   mutate(cluster = paises$cluster_km2)\nR> \nR> ggplot(pca_3d, aes(x = PC1, y = PC3, color = cluster, label = pais)) +\n+   geom_point(size = 3) +\n+   geom_text(vjust = -0.8, size = 3, show.legend = FALSE) +\n+   scale_color_manual(values = c(\"#2d4563\", \"#e63946\")) +\n+   labs(title = \"PC1 vs PC3\") +\n+   theme_minimal()\n```\n\n::: {.cell-output-display}\n![](11-laboratorio-05_files/figure-revealjs/ejercicio-pca3-1.png){fig-align='center' width=2400}\n:::\n:::\n\n:::\n\n# Continuar con el laboratorio de texto {background-color=\"#2d4563\"}\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}